// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: family.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyCommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok         bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	StatusCode int64  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FamilyCommonResponse) Reset() {
	*x = FamilyCommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyCommonResponse) ProtoMessage() {}

func (x *FamilyCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyCommonResponse.ProtoReflect.Descriptor instead.
func (*FamilyCommonResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyCommonResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *FamilyCommonResponse) GetStatusCode() int64 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FamilyCommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FamilyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyId uint64 `protobuf:"varint,1,opt,name=FamilyId,proto3" json:"FamilyId,omitempty"`
}

func (x *FamilyRequest) Reset() {
	*x = FamilyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyRequest) ProtoMessage() {}

func (x *FamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyRequest.ProtoReflect.Descriptor instead.
func (*FamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{1}
}

func (x *FamilyRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type FamilyHouseworkPointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyId uint64 `protobuf:"varint,2,opt,name=familyId,proto3" json:"familyId,omitempty"`
}

func (x *FamilyHouseworkPointRequest) Reset() {
	*x = FamilyHouseworkPointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyHouseworkPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyHouseworkPointRequest) ProtoMessage() {}

func (x *FamilyHouseworkPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyHouseworkPointRequest.ProtoReflect.Descriptor instead.
func (*FamilyHouseworkPointRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{2}
}

func (x *FamilyHouseworkPointRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type FamilyHouseworkPointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseworkPoint []*FamilyHouseworkPoint `protobuf:"bytes,1,rep,name=houseworkPoint,proto3" json:"houseworkPoint,omitempty"`
}

func (x *FamilyHouseworkPointResponse) Reset() {
	*x = FamilyHouseworkPointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyHouseworkPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyHouseworkPointResponse) ProtoMessage() {}

func (x *FamilyHouseworkPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyHouseworkPointResponse.ProtoReflect.Descriptor instead.
func (*FamilyHouseworkPointResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{3}
}

func (x *FamilyHouseworkPointResponse) GetHouseworkPoint() []*FamilyHouseworkPoint {
	if x != nil {
		return x.HouseworkPoint
	}
	return nil
}

type FamilyHouseworkPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User      *FamilyUserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Point     int64           `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	CreatedAt int64           `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64           `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *FamilyHouseworkPoint) Reset() {
	*x = FamilyHouseworkPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyHouseworkPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyHouseworkPoint) ProtoMessage() {}

func (x *FamilyHouseworkPoint) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyHouseworkPoint.ProtoReflect.Descriptor instead.
func (*FamilyHouseworkPoint) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{4}
}

func (x *FamilyHouseworkPoint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyHouseworkPoint) GetUser() *FamilyUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *FamilyHouseworkPoint) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *FamilyHouseworkPoint) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FamilyHouseworkPoint) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type AddFamilyMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FamilyId uint64 `protobuf:"varint,3,opt,name=familyId,proto3" json:"familyId,omitempty"`
}

func (x *AddFamilyMemberRequest) Reset() {
	*x = AddFamilyMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFamilyMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFamilyMemberRequest) ProtoMessage() {}

func (x *AddFamilyMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFamilyMemberRequest.ProtoReflect.Descriptor instead.
func (*AddFamilyMemberRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{5}
}

func (x *AddFamilyMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddFamilyMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddFamilyMemberRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type FamilyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Family *Family `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
}

func (x *FamilyResponse) Reset() {
	*x = FamilyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyResponse) ProtoMessage() {}

func (x *FamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyResponse.ProtoReflect.Descriptor instead.
func (*FamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{6}
}

func (x *FamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type FamilyUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *FamilyUserInfo) Reset() {
	*x = FamilyUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyUserInfo) ProtoMessage() {}

func (x *FamilyUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyUserInfo.ProtoReflect.Descriptor instead.
func (*FamilyUserInfo) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{7}
}

func (x *FamilyUserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FamilyUserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type Family struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User             []*FamilyUserInfo `protobuf:"bytes,2,rep,name=user,proto3" json:"user,omitempty"`
	Name             string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PointPerWorkTime string            `protobuf:"bytes,4,opt,name=pointPerWorkTime,proto3" json:"pointPerWorkTime,omitempty"`
}

func (x *Family) Reset() {
	*x = Family{}
	if protoimpl.UnsafeEnabled {
		mi := &file_family_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{8}
}

func (x *Family) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Family) GetUser() []*FamilyUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Family) GetPointPerWorkTime() string {
	if x != nil {
		return x.PointPerWorkTime
	}
	return ""
}

var File_family_proto protoreflect.FileDescriptor

var file_family_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x73, 0x68, 0x77, 0x22, 0x60, 0x0a, 0x14, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x0d, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x49, 0x64, 0x22, 0x39, 0x0a, 0x1b, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x61, 0x0a,
	0x1c, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x0e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x22, 0xa1, 0x01, 0x0a, 0x14, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x5e, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x22, 0x48, 0x0a, 0x0e, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x06, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x27, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a,
	0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x50, 0x65,
	0x72, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xc2, 0x02, 0x0a, 0x0d, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x12, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73,
	0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x12, 0x0b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79,
	0x1a, 0x19, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x0b, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x77,
	0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x0b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a,
	0x5a, 0x08, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_family_proto_rawDescOnce sync.Once
	file_family_proto_rawDescData = file_family_proto_rawDesc
)

func file_family_proto_rawDescGZIP() []byte {
	file_family_proto_rawDescOnce.Do(func() {
		file_family_proto_rawDescData = protoimpl.X.CompressGZIP(file_family_proto_rawDescData)
	})
	return file_family_proto_rawDescData
}

var file_family_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_family_proto_goTypes = []interface{}{
	(*FamilyCommonResponse)(nil),         // 0: shw.FamilyCommonResponse
	(*FamilyRequest)(nil),                // 1: shw.FamilyRequest
	(*FamilyHouseworkPointRequest)(nil),  // 2: shw.FamilyHouseworkPointRequest
	(*FamilyHouseworkPointResponse)(nil), // 3: shw.FamilyHouseworkPointResponse
	(*FamilyHouseworkPoint)(nil),         // 4: shw.FamilyHouseworkPoint
	(*AddFamilyMemberRequest)(nil),       // 5: shw.AddFamilyMemberRequest
	(*FamilyResponse)(nil),               // 6: shw.FamilyResponse
	(*FamilyUserInfo)(nil),               // 7: shw.FamilyUserInfo
	(*Family)(nil),                       // 8: shw.Family
}
var file_family_proto_depIdxs = []int32{
	4, // 0: shw.FamilyHouseworkPointResponse.houseworkPoint:type_name -> shw.FamilyHouseworkPoint
	7, // 1: shw.FamilyHouseworkPoint.user:type_name -> shw.FamilyUserInfo
	8, // 2: shw.FamilyResponse.family:type_name -> shw.Family
	7, // 3: shw.Family.user:type_name -> shw.FamilyUserInfo
	1, // 4: shw.FamilyService.GetFamily:input_type -> shw.FamilyRequest
	8, // 5: shw.FamilyService.CreateFamily:input_type -> shw.Family
	8, // 6: shw.FamilyService.UpdateFamily:input_type -> shw.Family
	8, // 7: shw.FamilyService.DeleteFamily:input_type -> shw.Family
	5, // 8: shw.FamilyService.AddFamilyMember:input_type -> shw.AddFamilyMemberRequest
	6, // 9: shw.FamilyService.GetFamily:output_type -> shw.FamilyResponse
	0, // 10: shw.FamilyService.CreateFamily:output_type -> shw.FamilyCommonResponse
	0, // 11: shw.FamilyService.UpdateFamily:output_type -> shw.FamilyCommonResponse
	0, // 12: shw.FamilyService.DeleteFamily:output_type -> shw.FamilyCommonResponse
	0, // 13: shw.FamilyService.AddFamilyMember:output_type -> shw.FamilyCommonResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_family_proto_init() }
func file_family_proto_init() {
	if File_family_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_family_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyCommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyHouseworkPointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyHouseworkPointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyHouseworkPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFamilyMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_family_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Family); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_family_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_family_proto_goTypes,
		DependencyIndexes: file_family_proto_depIdxs,
		MessageInfos:      file_family_proto_msgTypes,
	}.Build()
	File_family_proto = out.File
	file_family_proto_rawDesc = nil
	file_family_proto_goTypes = nil
	file_family_proto_depIdxs = nil
}
