// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: family.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FamilyServiceClient is the client API for FamilyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FamilyServiceClient interface {
	GetFamily(ctx context.Context, in *FamilyRequest, opts ...grpc.CallOption) (*FamilyResponse, error)
	CreateFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error)
	UpdateFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error)
	DeleteFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error)
	AddFamilyMember(ctx context.Context, in *AddFamilyMemberRequest, opts ...grpc.CallOption) (*CommonResponse, error)
}

type familyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFamilyServiceClient(cc grpc.ClientConnInterface) FamilyServiceClient {
	return &familyServiceClient{cc}
}

func (c *familyServiceClient) GetFamily(ctx context.Context, in *FamilyRequest, opts ...grpc.CallOption) (*FamilyResponse, error) {
	out := new(FamilyResponse)
	err := c.cc.Invoke(ctx, "/shw.FamilyService/GetFamily", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) CreateFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/shw.FamilyService/CreateFamily", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) UpdateFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/shw.FamilyService/UpdateFamily", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) DeleteFamily(ctx context.Context, in *Family, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/shw.FamilyService/DeleteFamily", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyServiceClient) AddFamilyMember(ctx context.Context, in *AddFamilyMemberRequest, opts ...grpc.CallOption) (*CommonResponse, error) {
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, "/shw.FamilyService/AddFamilyMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FamilyServiceServer is the server API for FamilyService service.
// All implementations must embed UnimplementedFamilyServiceServer
// for forward compatibility
type FamilyServiceServer interface {
	GetFamily(context.Context, *FamilyRequest) (*FamilyResponse, error)
	CreateFamily(context.Context, *Family) (*CommonResponse, error)
	UpdateFamily(context.Context, *Family) (*CommonResponse, error)
	DeleteFamily(context.Context, *Family) (*CommonResponse, error)
	AddFamilyMember(context.Context, *AddFamilyMemberRequest) (*CommonResponse, error)
	mustEmbedUnimplementedFamilyServiceServer()
}

// UnimplementedFamilyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFamilyServiceServer struct {
}

func (UnimplementedFamilyServiceServer) GetFamily(context.Context, *FamilyRequest) (*FamilyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFamily not implemented")
}
func (UnimplementedFamilyServiceServer) CreateFamily(context.Context, *Family) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFamily not implemented")
}
func (UnimplementedFamilyServiceServer) UpdateFamily(context.Context, *Family) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFamily not implemented")
}
func (UnimplementedFamilyServiceServer) DeleteFamily(context.Context, *Family) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFamily not implemented")
}
func (UnimplementedFamilyServiceServer) AddFamilyMember(context.Context, *AddFamilyMemberRequest) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFamilyMember not implemented")
}
func (UnimplementedFamilyServiceServer) mustEmbedUnimplementedFamilyServiceServer() {}

// UnsafeFamilyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FamilyServiceServer will
// result in compilation errors.
type UnsafeFamilyServiceServer interface {
	mustEmbedUnimplementedFamilyServiceServer()
}

func RegisterFamilyServiceServer(s grpc.ServiceRegistrar, srv FamilyServiceServer) {
	s.RegisterService(&FamilyService_ServiceDesc, srv)
}

func _FamilyService_GetFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).GetFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.FamilyService/GetFamily",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).GetFamily(ctx, req.(*FamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_CreateFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Family)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).CreateFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.FamilyService/CreateFamily",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).CreateFamily(ctx, req.(*Family))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_UpdateFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Family)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).UpdateFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.FamilyService/UpdateFamily",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).UpdateFamily(ctx, req.(*Family))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_DeleteFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Family)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).DeleteFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.FamilyService/DeleteFamily",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).DeleteFamily(ctx, req.(*Family))
	}
	return interceptor(ctx, in, info, handler)
}

func _FamilyService_AddFamilyMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFamilyMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FamilyServiceServer).AddFamilyMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.FamilyService/AddFamilyMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FamilyServiceServer).AddFamilyMember(ctx, req.(*AddFamilyMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FamilyService_ServiceDesc is the grpc.ServiceDesc for FamilyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FamilyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shw.FamilyService",
	HandlerType: (*FamilyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFamily",
			Handler:    _FamilyService_GetFamily_Handler,
		},
		{
			MethodName: "CreateFamily",
			Handler:    _FamilyService_CreateFamily_Handler,
		},
		{
			MethodName: "UpdateFamily",
			Handler:    _FamilyService_UpdateFamily_Handler,
		},
		{
			MethodName: "DeleteFamily",
			Handler:    _FamilyService_DeleteFamily_Handler,
		},
		{
			MethodName: "AddFamilyMember",
			Handler:    _FamilyService_AddFamilyMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "family.proto",
}
