// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: family.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // was familyId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRequest) Reset() {
	*x = GetFamilyRequest{}
	mi := &file_family_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRequest) ProtoMessage() {}

func (x *GetFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{0}
}

func (x *GetFamilyRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type GetFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyResponse) Reset() {
	*x = GetFamilyResponse{}
	mi := &file_family_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyResponse) ProtoMessage() {}

func (x *GetFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyResponse.ProtoReflect.Descriptor instead.
func (*GetFamilyResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{1}
}

func (x *GetFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type CreateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRequest) Reset() {
	*x = CreateFamilyRequest{}
	mi := &file_family_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRequest) ProtoMessage() {}

func (x *CreateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFamilyRequest) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type UpdateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFamilyRequest) Reset() {
	*x = UpdateFamilyRequest{}
	mi := &file_family_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFamilyRequest) ProtoMessage() {}

func (x *UpdateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFamilyRequest.ProtoReflect.Descriptor instead.
func (*UpdateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFamilyRequest) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type DeleteFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFamilyRequest) Reset() {
	*x = DeleteFamilyRequest{}
	mi := &file_family_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFamilyRequest) ProtoMessage() {}

func (x *DeleteFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFamilyRequest.ProtoReflect.Descriptor instead.
func (*DeleteFamilyRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFamilyRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type AddFamilyMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,3,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFamilyMemberRequest) Reset() {
	*x = AddFamilyMemberRequest{}
	mi := &file_family_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFamilyMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFamilyMemberRequest) ProtoMessage() {}

func (x *AddFamilyMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFamilyMemberRequest.ProtoReflect.Descriptor instead.
func (*AddFamilyMemberRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{5}
}

func (x *AddFamilyMemberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddFamilyMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddFamilyMemberRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type Family struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_family_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{6}
}

func (x *Family) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Family) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Family) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFamilyRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyRolesRequest) Reset() {
	*x = ListFamilyRolesRequest{}
	mi := &file_family_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyRolesRequest) ProtoMessage() {}

func (x *ListFamilyRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyRolesRequest.ProtoReflect.Descriptor instead.
func (*ListFamilyRolesRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{7}
}

func (x *ListFamilyRolesRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListFamilyRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*FamilyRole          `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"` // was family_role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyRolesResponse) Reset() {
	*x = ListFamilyRolesResponse{}
	mi := &file_family_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyRolesResponse) ProtoMessage() {}

func (x *ListFamilyRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyRolesResponse.ProtoReflect.Descriptor instead.
func (*ListFamilyRolesResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{8}
}

func (x *ListFamilyRolesResponse) GetRoles() []*FamilyRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetFamilyRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyRoleId  uint64                 `protobuf:"varint,1,opt,name=family_role_id,json=familyRoleId,proto3" json:"family_role_id,omitempty"` // was FamilyRoleRequest.family_role_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRoleRequest) Reset() {
	*x = GetFamilyRoleRequest{}
	mi := &file_family_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRoleRequest) ProtoMessage() {}

func (x *GetFamilyRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRoleRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRoleRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{9}
}

func (x *GetFamilyRoleRequest) GetFamilyRoleId() uint64 {
	if x != nil {
		return x.FamilyRoleId
	}
	return 0
}

type GetFamilyRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *FamilyRole            `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRoleResponse) Reset() {
	*x = GetFamilyRoleResponse{}
	mi := &file_family_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRoleResponse) ProtoMessage() {}

func (x *GetFamilyRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRoleResponse.ProtoReflect.Descriptor instead.
func (*GetFamilyRoleResponse) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{10}
}

func (x *GetFamilyRoleResponse) GetRole() *FamilyRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type CreateFamilyRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *FamilyRole            `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRoleRequest) Reset() {
	*x = CreateFamilyRoleRequest{}
	mi := &file_family_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRoleRequest) ProtoMessage() {}

func (x *CreateFamilyRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRoleRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{11}
}

func (x *CreateFamilyRoleRequest) GetRole() *FamilyRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateFamilyRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *FamilyRole            `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFamilyRoleRequest) Reset() {
	*x = UpdateFamilyRoleRequest{}
	mi := &file_family_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFamilyRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFamilyRoleRequest) ProtoMessage() {}

func (x *UpdateFamilyRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFamilyRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateFamilyRoleRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFamilyRoleRequest) GetRole() *FamilyRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteFamilyRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyRoleId  uint64                 `protobuf:"varint,1,opt,name=family_role_id,json=familyRoleId,proto3" json:"family_role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFamilyRoleRequest) Reset() {
	*x = DeleteFamilyRoleRequest{}
	mi := &file_family_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFamilyRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFamilyRoleRequest) ProtoMessage() {}

func (x *DeleteFamilyRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFamilyRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteFamilyRoleRequest) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteFamilyRoleRequest) GetFamilyRoleId() uint64 {
	if x != nil {
		return x.FamilyRoleId
	}
	return 0
}

type FamilyRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,4,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyRole) Reset() {
	*x = FamilyRole{}
	mi := &file_family_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyRole) ProtoMessage() {}

func (x *FamilyRole) ProtoReflect() protoreflect.Message {
	mi := &file_family_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyRole.ProtoReflect.Descriptor instead.
func (*FamilyRole) Descriptor() ([]byte, []int) {
	return file_family_proto_rawDescGZIP(), []int{14}
}

func (x *FamilyRole) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FamilyRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FamilyRole) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

var File_family_proto protoreflect.FileDescriptor

const file_family_proto_rawDesc = "" +
	"\n" +
	"\ffamily.proto\x12\x03shw\x1a\fcommon.proto\"/\n" +
	"\x10GetFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"8\n" +
	"\x11GetFamilyResponse\x12#\n" +
	"\x06family\x18\x01 \x01(\v2\v.shw.FamilyR\x06family\":\n" +
	"\x13CreateFamilyRequest\x12#\n" +
	"\x06family\x18\x01 \x01(\v2\v.shw.FamilyR\x06family\":\n" +
	"\x13UpdateFamilyRequest\x12#\n" +
	"\x06family\x18\x01 \x01(\v2\v.shw.FamilyR\x06family\"2\n" +
	"\x13DeleteFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"_\n" +
	"\x16AddFamilyMemberRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfamily_id\x18\x03 \x01(\x04R\bfamilyId\"Q\n" +
	"\x06Family\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\x05users\x18\x02 \x03(\v2\r.shw.UserInfoR\x05users\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"5\n" +
	"\x16ListFamilyRolesRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"@\n" +
	"\x17ListFamilyRolesResponse\x12%\n" +
	"\x05roles\x18\x01 \x03(\v2\x0f.shw.FamilyRoleR\x05roles\"<\n" +
	"\x14GetFamilyRoleRequest\x12$\n" +
	"\x0efamily_role_id\x18\x01 \x01(\x04R\ffamilyRoleId\"<\n" +
	"\x15GetFamilyRoleResponse\x12#\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.shw.FamilyRoleR\x04role\">\n" +
	"\x17CreateFamilyRoleRequest\x12#\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.shw.FamilyRoleR\x04role\">\n" +
	"\x17UpdateFamilyRoleRequest\x12#\n" +
	"\x04role\x18\x01 \x01(\v2\x0f.shw.FamilyRoleR\x04role\"?\n" +
	"\x17DeleteFamilyRoleRequest\x12$\n" +
	"\x0efamily_role_id\x18\x01 \x01(\x04R\ffamilyRoleId\"o\n" +
	"\n" +
	"FamilyRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfamily_id\x18\x04 \x01(\x04R\bfamilyId2\xd7\x02\n" +
	"\rFamilyService\x12<\n" +
	"\tGetFamily\x12\x15.shw.GetFamilyRequest\x1a\x16.shw.GetFamilyResponse\"\x00\x12?\n" +
	"\fCreateFamily\x12\x18.shw.CreateFamilyRequest\x1a\x13.shw.CommonResponse\"\x00\x12?\n" +
	"\fUpdateFamily\x12\x18.shw.UpdateFamilyRequest\x1a\x13.shw.CommonResponse\"\x00\x12?\n" +
	"\fDeleteFamily\x12\x18.shw.DeleteFamilyRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fAddFamilyMember\x12\x1b.shw.AddFamilyMemberRequest\x1a\x13.shw.CommonResponse\"\x002\x88\x03\n" +
	"\x11FamilyRoleService\x12N\n" +
	"\x0fListFamilyRoles\x12\x1b.shw.ListFamilyRolesRequest\x1a\x1c.shw.ListFamilyRolesResponse\"\x00\x12H\n" +
	"\rGetFamilyRole\x12\x19.shw.GetFamilyRoleRequest\x1a\x1a.shw.GetFamilyRoleResponse\"\x00\x12G\n" +
	"\x10CreateFamilyRole\x12\x1c.shw.CreateFamilyRoleRequest\x1a\x13.shw.CommonResponse\"\x00\x12G\n" +
	"\x10UpdateFamilyRole\x12\x1c.shw.UpdateFamilyRoleRequest\x1a\x13.shw.CommonResponse\"\x00\x12G\n" +
	"\x10DeleteFamilyRole\x12\x1c.shw.DeleteFamilyRoleRequest\x1a\x13.shw.CommonResponse\"\x00B\x12Z\x10shwgrpc/pkg/grpcb\x06proto3"

var (
	file_family_proto_rawDescOnce sync.Once
	file_family_proto_rawDescData []byte
)

func file_family_proto_rawDescGZIP() []byte {
	file_family_proto_rawDescOnce.Do(func() {
		file_family_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)))
	})
	return file_family_proto_rawDescData
}

var file_family_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_family_proto_goTypes = []any{
	(*GetFamilyRequest)(nil),        // 0: shw.GetFamilyRequest
	(*GetFamilyResponse)(nil),       // 1: shw.GetFamilyResponse
	(*CreateFamilyRequest)(nil),     // 2: shw.CreateFamilyRequest
	(*UpdateFamilyRequest)(nil),     // 3: shw.UpdateFamilyRequest
	(*DeleteFamilyRequest)(nil),     // 4: shw.DeleteFamilyRequest
	(*AddFamilyMemberRequest)(nil),  // 5: shw.AddFamilyMemberRequest
	(*Family)(nil),                  // 6: shw.Family
	(*ListFamilyRolesRequest)(nil),  // 7: shw.ListFamilyRolesRequest
	(*ListFamilyRolesResponse)(nil), // 8: shw.ListFamilyRolesResponse
	(*GetFamilyRoleRequest)(nil),    // 9: shw.GetFamilyRoleRequest
	(*GetFamilyRoleResponse)(nil),   // 10: shw.GetFamilyRoleResponse
	(*CreateFamilyRoleRequest)(nil), // 11: shw.CreateFamilyRoleRequest
	(*UpdateFamilyRoleRequest)(nil), // 12: shw.UpdateFamilyRoleRequest
	(*DeleteFamilyRoleRequest)(nil), // 13: shw.DeleteFamilyRoleRequest
	(*FamilyRole)(nil),              // 14: shw.FamilyRole
	(*UserInfo)(nil),                // 15: shw.UserInfo
	(*CommonResponse)(nil),          // 16: shw.CommonResponse
}
var file_family_proto_depIdxs = []int32{
	6,  // 0: shw.GetFamilyResponse.family:type_name -> shw.Family
	6,  // 1: shw.CreateFamilyRequest.family:type_name -> shw.Family
	6,  // 2: shw.UpdateFamilyRequest.family:type_name -> shw.Family
	15, // 3: shw.Family.users:type_name -> shw.UserInfo
	14, // 4: shw.ListFamilyRolesResponse.roles:type_name -> shw.FamilyRole
	14, // 5: shw.GetFamilyRoleResponse.role:type_name -> shw.FamilyRole
	14, // 6: shw.CreateFamilyRoleRequest.role:type_name -> shw.FamilyRole
	14, // 7: shw.UpdateFamilyRoleRequest.role:type_name -> shw.FamilyRole
	0,  // 8: shw.FamilyService.GetFamily:input_type -> shw.GetFamilyRequest
	2,  // 9: shw.FamilyService.CreateFamily:input_type -> shw.CreateFamilyRequest
	3,  // 10: shw.FamilyService.UpdateFamily:input_type -> shw.UpdateFamilyRequest
	4,  // 11: shw.FamilyService.DeleteFamily:input_type -> shw.DeleteFamilyRequest
	5,  // 12: shw.FamilyService.AddFamilyMember:input_type -> shw.AddFamilyMemberRequest
	7,  // 13: shw.FamilyRoleService.ListFamilyRoles:input_type -> shw.ListFamilyRolesRequest
	9,  // 14: shw.FamilyRoleService.GetFamilyRole:input_type -> shw.GetFamilyRoleRequest
	11, // 15: shw.FamilyRoleService.CreateFamilyRole:input_type -> shw.CreateFamilyRoleRequest
	12, // 16: shw.FamilyRoleService.UpdateFamilyRole:input_type -> shw.UpdateFamilyRoleRequest
	13, // 17: shw.FamilyRoleService.DeleteFamilyRole:input_type -> shw.DeleteFamilyRoleRequest
	1,  // 18: shw.FamilyService.GetFamily:output_type -> shw.GetFamilyResponse
	16, // 19: shw.FamilyService.CreateFamily:output_type -> shw.CommonResponse
	16, // 20: shw.FamilyService.UpdateFamily:output_type -> shw.CommonResponse
	16, // 21: shw.FamilyService.DeleteFamily:output_type -> shw.CommonResponse
	16, // 22: shw.FamilyService.AddFamilyMember:output_type -> shw.CommonResponse
	8,  // 23: shw.FamilyRoleService.ListFamilyRoles:output_type -> shw.ListFamilyRolesResponse
	10, // 24: shw.FamilyRoleService.GetFamilyRole:output_type -> shw.GetFamilyRoleResponse
	16, // 25: shw.FamilyRoleService.CreateFamilyRole:output_type -> shw.CommonResponse
	16, // 26: shw.FamilyRoleService.UpdateFamilyRole:output_type -> shw.CommonResponse
	16, // 27: shw.FamilyRoleService.DeleteFamilyRole:output_type -> shw.CommonResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_family_proto_init() }
func file_family_proto_init() {
	if File_family_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_family_proto_rawDesc), len(file_family_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_family_proto_goTypes,
		DependencyIndexes: file_family_proto_depIdxs,
		MessageInfos:      file_family_proto_msgTypes,
	}.Build()
	File_family_proto = out.File
	file_family_proto_goTypes = nil
	file_family_proto_depIdxs = nil
}
