// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: housework.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HouseworkServiceClient is the client API for HouseworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HouseworkServiceClient interface {
	GetHousework(ctx context.Context, in *HouseworkRequest, opts ...grpc.CallOption) (*HouseworkResponse, error)
	GetHouseworkDetail(ctx context.Context, in *HouseworkDetailRequest, opts ...grpc.CallOption) (*HouseworkDetailResponse, error)
	CreateHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	UpdateHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	FinishHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	DeleteHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	GetHouseworkMemo(ctx context.Context, in *HouseworkMemoRequest, opts ...grpc.CallOption) (*HouseworkMemoResponse, error)
	CreateHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	UpdateHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	DeleteHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error)
	GetHouseworkPoint(ctx context.Context, in *HouseworkPointRequest, opts ...grpc.CallOption) (*HouseworkPointResponse, error)
	GetHouseworkPointHistory(ctx context.Context, in *HouseworkPointHistoryRequest, opts ...grpc.CallOption) (*HouseworkPointHistoryResponse, error)
}

type houseworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHouseworkServiceClient(cc grpc.ClientConnInterface) HouseworkServiceClient {
	return &houseworkServiceClient{cc}
}

func (c *houseworkServiceClient) GetHousework(ctx context.Context, in *HouseworkRequest, opts ...grpc.CallOption) (*HouseworkResponse, error) {
	out := new(HouseworkResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/GetHousework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) GetHouseworkDetail(ctx context.Context, in *HouseworkDetailRequest, opts ...grpc.CallOption) (*HouseworkDetailResponse, error) {
	out := new(HouseworkDetailResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/GetHouseworkDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) CreateHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/CreateHousework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) UpdateHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/UpdateHousework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) FinishHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/FinishHousework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) DeleteHousework(ctx context.Context, in *Housework, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/DeleteHousework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) GetHouseworkMemo(ctx context.Context, in *HouseworkMemoRequest, opts ...grpc.CallOption) (*HouseworkMemoResponse, error) {
	out := new(HouseworkMemoResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/GetHouseworkMemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) CreateHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/CreateHouseworkMemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) UpdateHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/UpdateHouseworkMemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) DeleteHouseworkMemo(ctx context.Context, in *HouseworkMemo, opts ...grpc.CallOption) (*HouseworkCommonResponse, error) {
	out := new(HouseworkCommonResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/DeleteHouseworkMemo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) GetHouseworkPoint(ctx context.Context, in *HouseworkPointRequest, opts ...grpc.CallOption) (*HouseworkPointResponse, error) {
	out := new(HouseworkPointResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/GetHouseworkPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseworkServiceClient) GetHouseworkPointHistory(ctx context.Context, in *HouseworkPointHistoryRequest, opts ...grpc.CallOption) (*HouseworkPointHistoryResponse, error) {
	out := new(HouseworkPointHistoryResponse)
	err := c.cc.Invoke(ctx, "/shw.HouseworkService/GetHouseworkPointHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HouseworkServiceServer is the server API for HouseworkService service.
// All implementations must embed UnimplementedHouseworkServiceServer
// for forward compatibility
type HouseworkServiceServer interface {
	GetHousework(context.Context, *HouseworkRequest) (*HouseworkResponse, error)
	GetHouseworkDetail(context.Context, *HouseworkDetailRequest) (*HouseworkDetailResponse, error)
	CreateHousework(context.Context, *Housework) (*HouseworkCommonResponse, error)
	UpdateHousework(context.Context, *Housework) (*HouseworkCommonResponse, error)
	FinishHousework(context.Context, *Housework) (*HouseworkCommonResponse, error)
	DeleteHousework(context.Context, *Housework) (*HouseworkCommonResponse, error)
	GetHouseworkMemo(context.Context, *HouseworkMemoRequest) (*HouseworkMemoResponse, error)
	CreateHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error)
	UpdateHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error)
	DeleteHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error)
	GetHouseworkPoint(context.Context, *HouseworkPointRequest) (*HouseworkPointResponse, error)
	GetHouseworkPointHistory(context.Context, *HouseworkPointHistoryRequest) (*HouseworkPointHistoryResponse, error)
	mustEmbedUnimplementedHouseworkServiceServer()
}

// UnimplementedHouseworkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHouseworkServiceServer struct {
}

func (UnimplementedHouseworkServiceServer) GetHousework(context.Context, *HouseworkRequest) (*HouseworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHousework not implemented")
}
func (UnimplementedHouseworkServiceServer) GetHouseworkDetail(context.Context, *HouseworkDetailRequest) (*HouseworkDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouseworkDetail not implemented")
}
func (UnimplementedHouseworkServiceServer) CreateHousework(context.Context, *Housework) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHousework not implemented")
}
func (UnimplementedHouseworkServiceServer) UpdateHousework(context.Context, *Housework) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHousework not implemented")
}
func (UnimplementedHouseworkServiceServer) FinishHousework(context.Context, *Housework) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishHousework not implemented")
}
func (UnimplementedHouseworkServiceServer) DeleteHousework(context.Context, *Housework) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHousework not implemented")
}
func (UnimplementedHouseworkServiceServer) GetHouseworkMemo(context.Context, *HouseworkMemoRequest) (*HouseworkMemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouseworkMemo not implemented")
}
func (UnimplementedHouseworkServiceServer) CreateHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouseworkMemo not implemented")
}
func (UnimplementedHouseworkServiceServer) UpdateHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHouseworkMemo not implemented")
}
func (UnimplementedHouseworkServiceServer) DeleteHouseworkMemo(context.Context, *HouseworkMemo) (*HouseworkCommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHouseworkMemo not implemented")
}
func (UnimplementedHouseworkServiceServer) GetHouseworkPoint(context.Context, *HouseworkPointRequest) (*HouseworkPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouseworkPoint not implemented")
}
func (UnimplementedHouseworkServiceServer) GetHouseworkPointHistory(context.Context, *HouseworkPointHistoryRequest) (*HouseworkPointHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouseworkPointHistory not implemented")
}
func (UnimplementedHouseworkServiceServer) mustEmbedUnimplementedHouseworkServiceServer() {}

// UnsafeHouseworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HouseworkServiceServer will
// result in compilation errors.
type UnsafeHouseworkServiceServer interface {
	mustEmbedUnimplementedHouseworkServiceServer()
}

func RegisterHouseworkServiceServer(s grpc.ServiceRegistrar, srv HouseworkServiceServer) {
	s.RegisterService(&HouseworkService_ServiceDesc, srv)
}

func _HouseworkService_GetHousework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).GetHousework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/GetHousework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).GetHousework(ctx, req.(*HouseworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_GetHouseworkDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).GetHouseworkDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/GetHouseworkDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).GetHouseworkDetail(ctx, req.(*HouseworkDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_CreateHousework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Housework)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).CreateHousework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/CreateHousework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).CreateHousework(ctx, req.(*Housework))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_UpdateHousework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Housework)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).UpdateHousework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/UpdateHousework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).UpdateHousework(ctx, req.(*Housework))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_FinishHousework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Housework)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).FinishHousework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/FinishHousework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).FinishHousework(ctx, req.(*Housework))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_DeleteHousework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Housework)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).DeleteHousework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/DeleteHousework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).DeleteHousework(ctx, req.(*Housework))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_GetHouseworkMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkMemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).GetHouseworkMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/GetHouseworkMemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).GetHouseworkMemo(ctx, req.(*HouseworkMemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_CreateHouseworkMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkMemo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).CreateHouseworkMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/CreateHouseworkMemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).CreateHouseworkMemo(ctx, req.(*HouseworkMemo))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_UpdateHouseworkMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkMemo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).UpdateHouseworkMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/UpdateHouseworkMemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).UpdateHouseworkMemo(ctx, req.(*HouseworkMemo))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_DeleteHouseworkMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkMemo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).DeleteHouseworkMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/DeleteHouseworkMemo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).DeleteHouseworkMemo(ctx, req.(*HouseworkMemo))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_GetHouseworkPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).GetHouseworkPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/GetHouseworkPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).GetHouseworkPoint(ctx, req.(*HouseworkPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseworkService_GetHouseworkPointHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HouseworkPointHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseworkServiceServer).GetHouseworkPointHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shw.HouseworkService/GetHouseworkPointHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseworkServiceServer).GetHouseworkPointHistory(ctx, req.(*HouseworkPointHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HouseworkService_ServiceDesc is the grpc.ServiceDesc for HouseworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HouseworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shw.HouseworkService",
	HandlerType: (*HouseworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHousework",
			Handler:    _HouseworkService_GetHousework_Handler,
		},
		{
			MethodName: "GetHouseworkDetail",
			Handler:    _HouseworkService_GetHouseworkDetail_Handler,
		},
		{
			MethodName: "CreateHousework",
			Handler:    _HouseworkService_CreateHousework_Handler,
		},
		{
			MethodName: "UpdateHousework",
			Handler:    _HouseworkService_UpdateHousework_Handler,
		},
		{
			MethodName: "FinishHousework",
			Handler:    _HouseworkService_FinishHousework_Handler,
		},
		{
			MethodName: "DeleteHousework",
			Handler:    _HouseworkService_DeleteHousework_Handler,
		},
		{
			MethodName: "GetHouseworkMemo",
			Handler:    _HouseworkService_GetHouseworkMemo_Handler,
		},
		{
			MethodName: "CreateHouseworkMemo",
			Handler:    _HouseworkService_CreateHouseworkMemo_Handler,
		},
		{
			MethodName: "UpdateHouseworkMemo",
			Handler:    _HouseworkService_UpdateHouseworkMemo_Handler,
		},
		{
			MethodName: "DeleteHouseworkMemo",
			Handler:    _HouseworkService_DeleteHouseworkMemo_Handler,
		},
		{
			MethodName: "GetHouseworkPoint",
			Handler:    _HouseworkService_GetHouseworkPoint_Handler,
		},
		{
			MethodName: "GetHouseworkPointHistory",
			Handler:    _HouseworkService_GetHouseworkPointHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "housework.proto",
}
