// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: housework.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HouseworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyId uint64 `protobuf:"varint,1,opt,name=familyId,proto3" json:"familyId,omitempty"`
}

func (x *HouseworkRequest) Reset() {
	*x = HouseworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkRequest) ProtoMessage() {}

func (x *HouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkRequest.ProtoReflect.Descriptor instead.
func (*HouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{0}
}

func (x *HouseworkRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type HouseworkTargetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HouseworkTargetRequest) Reset() {
	*x = HouseworkTargetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkTargetRequest) ProtoMessage() {}

func (x *HouseworkTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkTargetRequest.ProtoReflect.Descriptor instead.
func (*HouseworkTargetRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{1}
}

func (x *HouseworkTargetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HouseworkDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HouseworkDetailRequest) Reset() {
	*x = HouseworkDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkDetailRequest) ProtoMessage() {}

func (x *HouseworkDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkDetailRequest.ProtoReflect.Descriptor instead.
func (*HouseworkDetailRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{2}
}

func (x *HouseworkDetailRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HouseworkMemoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HouseworkId uint64 `protobuf:"varint,1,opt,name=houseworkId,proto3" json:"houseworkId,omitempty"`
}

func (x *HouseworkMemoRequest) Reset() {
	*x = HouseworkMemoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkMemoRequest) ProtoMessage() {}

func (x *HouseworkMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkMemoRequest.ProtoReflect.Descriptor instead.
func (*HouseworkMemoRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{3}
}

func (x *HouseworkMemoRequest) GetHouseworkId() uint64 {
	if x != nil {
		return x.HouseworkId
	}
	return 0
}

type HouseworkPointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *HouseworkPointRequest) Reset() {
	*x = HouseworkPointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointRequest) ProtoMessage() {}

func (x *HouseworkPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointRequest.ProtoReflect.Descriptor instead.
func (*HouseworkPointRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{4}
}

func (x *HouseworkPointRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HouseworkTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyId uint64 `protobuf:"varint,1,opt,name=familyId,proto3" json:"familyId,omitempty"`
}

func (x *HouseworkTemplateRequest) Reset() {
	*x = HouseworkTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkTemplateRequest) ProtoMessage() {}

func (x *HouseworkTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkTemplateRequest.ProtoReflect.Descriptor instead.
func (*HouseworkTemplateRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{5}
}

func (x *HouseworkTemplateRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type HouseworkPointHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *HouseworkPointHistoryRequest) Reset() {
	*x = HouseworkPointHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPointHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointHistoryRequest) ProtoMessage() {}

func (x *HouseworkPointHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointHistoryRequest.ProtoReflect.Descriptor instead.
func (*HouseworkPointHistoryRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{6}
}

func (x *HouseworkPointHistoryRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type HouseworkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Housework []*Housework `protobuf:"bytes,1,rep,name=housework,proto3" json:"housework,omitempty"`
}

func (x *HouseworkResponse) Reset() {
	*x = HouseworkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkResponse) ProtoMessage() {}

func (x *HouseworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkResponse.ProtoReflect.Descriptor instead.
func (*HouseworkResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{7}
}

func (x *HouseworkResponse) GetHousework() []*Housework {
	if x != nil {
		return x.Housework
	}
	return nil
}

type HouseworkDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Housework *Housework       `protobuf:"bytes,1,opt,name=housework,proto3" json:"housework,omitempty"`
	Memo      []*HouseworkMemo `protobuf:"bytes,2,rep,name=memo,proto3" json:"memo,omitempty"`
}

func (x *HouseworkDetailResponse) Reset() {
	*x = HouseworkDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkDetailResponse) ProtoMessage() {}

func (x *HouseworkDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkDetailResponse.ProtoReflect.Descriptor instead.
func (*HouseworkDetailResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{8}
}

func (x *HouseworkDetailResponse) GetHousework() *Housework {
	if x != nil {
		return x.Housework
	}
	return nil
}

func (x *HouseworkDetailResponse) GetMemo() []*HouseworkMemo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type HouseworkMemoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memo []*HouseworkMemo `protobuf:"bytes,1,rep,name=memo,proto3" json:"memo,omitempty"`
}

func (x *HouseworkMemoResponse) Reset() {
	*x = HouseworkMemoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkMemoResponse) ProtoMessage() {}

func (x *HouseworkMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkMemoResponse.ProtoReflect.Descriptor instead.
func (*HouseworkMemoResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{9}
}

func (x *HouseworkMemoResponse) GetMemo() []*HouseworkMemo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type HouseworkPointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Point *HouseworkPoint `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
}

func (x *HouseworkPointResponse) Reset() {
	*x = HouseworkPointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointResponse) ProtoMessage() {}

func (x *HouseworkPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointResponse.ProtoReflect.Descriptor instead.
func (*HouseworkPointResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{10}
}

func (x *HouseworkPointResponse) GetPoint() *HouseworkPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type HouseworkPointHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History []*HouseworkPointHistory `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *HouseworkPointHistoryResponse) Reset() {
	*x = HouseworkPointHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPointHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointHistoryResponse) ProtoMessage() {}

func (x *HouseworkPointHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointHistoryResponse.ProtoReflect.Descriptor instead.
func (*HouseworkPointHistoryResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{11}
}

func (x *HouseworkPointHistoryResponse) GetHistory() []*HouseworkPointHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type HouseworkTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Template []*HouseworkTemplate `protobuf:"bytes,1,rep,name=template,proto3" json:"template,omitempty"`
}

func (x *HouseworkTemplateResponse) Reset() {
	*x = HouseworkTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkTemplateResponse) ProtoMessage() {}

func (x *HouseworkTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkTemplateResponse.ProtoReflect.Descriptor instead.
func (*HouseworkTemplateResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{12}
}

func (x *HouseworkTemplateResponse) GetTemplate() []*HouseworkTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type Housework struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId  uint64    `protobuf:"varint,2,opt,name=familyId,proto3" json:"familyId,omitempty"`
	Title     string    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail    string    `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status    string    `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	WorkUser  *UserInfo `protobuf:"bytes,6,opt,name=workUser,proto3" json:"workUser,omitempty"`
	StartedAt int64     `protobuf:"varint,7,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	EndedAt   int64     `protobuf:"varint,8,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
}

func (x *Housework) Reset() {
	*x = Housework{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Housework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Housework) ProtoMessage() {}

func (x *Housework) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Housework.ProtoReflect.Descriptor instead.
func (*Housework) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{13}
}

func (x *Housework) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Housework) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *Housework) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Housework) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Housework) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Housework) GetWorkUser() *UserInfo {
	if x != nil {
		return x.WorkUser
	}
	return nil
}

func (x *Housework) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Housework) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type HouseworkMemo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseworkId uint64    `protobuf:"varint,2,opt,name=houseworkId,proto3" json:"houseworkId,omitempty"`
	Message     string    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SendFrom    *UserInfo `protobuf:"bytes,4,opt,name=sendFrom,proto3" json:"sendFrom,omitempty"`
	CreatedAt   int64     `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt   int64     `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *HouseworkMemo) Reset() {
	*x = HouseworkMemo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkMemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkMemo) ProtoMessage() {}

func (x *HouseworkMemo) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkMemo.ProtoReflect.Descriptor instead.
func (*HouseworkMemo) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{14}
}

func (x *HouseworkMemo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkMemo) GetHouseworkId() uint64 {
	if x != nil {
		return x.HouseworkId
	}
	return 0
}

func (x *HouseworkMemo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HouseworkMemo) GetSendFrom() *UserInfo {
	if x != nil {
		return x.SendFrom
	}
	return nil
}

func (x *HouseworkMemo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkMemo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User      *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Point     int64     `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	CreatedAt int64     `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64     `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *HouseworkPoint) Reset() {
	*x = HouseworkPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPoint) ProtoMessage() {}

func (x *HouseworkPoint) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPoint.ProtoReflect.Descriptor instead.
func (*HouseworkPoint) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{15}
}

func (x *HouseworkPoint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkPoint) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HouseworkPoint) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *HouseworkPoint) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkPoint) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkPointHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User      *UserInfo `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Detail    string    `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Point     int64     `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	CreatedAt int64     `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *HouseworkPointHistory) Reset() {
	*x = HouseworkPointHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkPointHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointHistory) ProtoMessage() {}

func (x *HouseworkPointHistory) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointHistory.ProtoReflect.Descriptor instead.
func (*HouseworkPointHistory) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{16}
}

func (x *HouseworkPointHistory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkPointHistory) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HouseworkPointHistory) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HouseworkPointHistory) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *HouseworkPointHistory) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type HouseworkTemplate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId  uint64 `protobuf:"varint,2,opt,name=familyId,proto3" json:"familyId,omitempty"`
	Title     string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail    string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt int64  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *HouseworkTemplate) Reset() {
	*x = HouseworkTemplate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_housework_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HouseworkTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkTemplate) ProtoMessage() {}

func (x *HouseworkTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkTemplate.ProtoReflect.Descriptor instead.
func (*HouseworkTemplate) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{17}
}

func (x *HouseworkTemplate) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkTemplate) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *HouseworkTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseworkTemplate) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HouseworkTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_housework_proto protoreflect.FileDescriptor

var file_housework_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x73, 0x68, 0x77, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28,
	0x0a, 0x16, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x14, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x18, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1c, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x11, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68,
	0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x09, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x6f, 0x0a, 0x17, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x52, 0x09, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x26, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d,
	0x6f, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22, 0x3f, 0x0a, 0x15, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65,
	0x6d, 0x6f, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x22, 0x43, 0x0a, 0x16, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x55, 0x0a,
	0x1d, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x07, 0x68, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x22, 0x4f, 0x0a, 0x19, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x08, 0x74, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x09, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x74, 0x22, 0xc2, 0x01, 0x0a, 0x0d, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x46, 0x72,
	0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x95, 0x01,
	0x0a, 0x0e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x21, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x73, 0x68, 0x77, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x15, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x21, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa9,
	0x01, 0x0a, 0x11, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xf0, 0x06, 0x0a, 0x10, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x15, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x51, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x1a, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x12, 0x0e, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x1a, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x77,
	0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x12, 0x1b, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72,
	0x6b, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x19, 0x2e, 0x73, 0x68, 0x77, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x12, 0x2e, 0x73, 0x68, 0x77, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x1a, 0x13, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x12, 0x2e, 0x73, 0x68,
	0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x1a,
	0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x12, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x4d, 0x65, 0x6d,
	0x6f, 0x1a, 0x13, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1a, 0x2e,
	0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x77, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x68, 0x77, 0x2e, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a,
	0x10, 0x73, 0x68, 0x77, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_housework_proto_rawDescOnce sync.Once
	file_housework_proto_rawDescData = file_housework_proto_rawDesc
)

func file_housework_proto_rawDescGZIP() []byte {
	file_housework_proto_rawDescOnce.Do(func() {
		file_housework_proto_rawDescData = protoimpl.X.CompressGZIP(file_housework_proto_rawDescData)
	})
	return file_housework_proto_rawDescData
}

var file_housework_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_housework_proto_goTypes = []interface{}{
	(*HouseworkRequest)(nil),              // 0: shw.HouseworkRequest
	(*HouseworkTargetRequest)(nil),        // 1: shw.HouseworkTargetRequest
	(*HouseworkDetailRequest)(nil),        // 2: shw.HouseworkDetailRequest
	(*HouseworkMemoRequest)(nil),          // 3: shw.HouseworkMemoRequest
	(*HouseworkPointRequest)(nil),         // 4: shw.HouseworkPointRequest
	(*HouseworkTemplateRequest)(nil),      // 5: shw.HouseworkTemplateRequest
	(*HouseworkPointHistoryRequest)(nil),  // 6: shw.HouseworkPointHistoryRequest
	(*HouseworkResponse)(nil),             // 7: shw.HouseworkResponse
	(*HouseworkDetailResponse)(nil),       // 8: shw.HouseworkDetailResponse
	(*HouseworkMemoResponse)(nil),         // 9: shw.HouseworkMemoResponse
	(*HouseworkPointResponse)(nil),        // 10: shw.HouseworkPointResponse
	(*HouseworkPointHistoryResponse)(nil), // 11: shw.HouseworkPointHistoryResponse
	(*HouseworkTemplateResponse)(nil),     // 12: shw.HouseworkTemplateResponse
	(*Housework)(nil),                     // 13: shw.Housework
	(*HouseworkMemo)(nil),                 // 14: shw.HouseworkMemo
	(*HouseworkPoint)(nil),                // 15: shw.HouseworkPoint
	(*HouseworkPointHistory)(nil),         // 16: shw.HouseworkPointHistory
	(*HouseworkTemplate)(nil),             // 17: shw.HouseworkTemplate
	(*UserInfo)(nil),                      // 18: shw.UserInfo
	(*CommonResponse)(nil),                // 19: shw.CommonResponse
}
var file_housework_proto_depIdxs = []int32{
	13, // 0: shw.HouseworkResponse.housework:type_name -> shw.Housework
	13, // 1: shw.HouseworkDetailResponse.housework:type_name -> shw.Housework
	14, // 2: shw.HouseworkDetailResponse.memo:type_name -> shw.HouseworkMemo
	14, // 3: shw.HouseworkMemoResponse.memo:type_name -> shw.HouseworkMemo
	15, // 4: shw.HouseworkPointResponse.point:type_name -> shw.HouseworkPoint
	16, // 5: shw.HouseworkPointHistoryResponse.history:type_name -> shw.HouseworkPointHistory
	17, // 6: shw.HouseworkTemplateResponse.template:type_name -> shw.HouseworkTemplate
	18, // 7: shw.Housework.workUser:type_name -> shw.UserInfo
	18, // 8: shw.HouseworkMemo.sendFrom:type_name -> shw.UserInfo
	18, // 9: shw.HouseworkPoint.user:type_name -> shw.UserInfo
	18, // 10: shw.HouseworkPointHistory.user:type_name -> shw.UserInfo
	0,  // 11: shw.HouseworkService.GetHousework:input_type -> shw.HouseworkRequest
	2,  // 12: shw.HouseworkService.GetHouseworkDetail:input_type -> shw.HouseworkDetailRequest
	13, // 13: shw.HouseworkService.CreateHousework:input_type -> shw.Housework
	13, // 14: shw.HouseworkService.UpdateHousework:input_type -> shw.Housework
	1,  // 15: shw.HouseworkService.FinishHousework:input_type -> shw.HouseworkTargetRequest
	1,  // 16: shw.HouseworkService.DeleteHousework:input_type -> shw.HouseworkTargetRequest
	3,  // 17: shw.HouseworkService.GetHouseworkMemo:input_type -> shw.HouseworkMemoRequest
	14, // 18: shw.HouseworkService.CreateHouseworkMemo:input_type -> shw.HouseworkMemo
	14, // 19: shw.HouseworkService.UpdateHouseworkMemo:input_type -> shw.HouseworkMemo
	14, // 20: shw.HouseworkService.DeleteHouseworkMemo:input_type -> shw.HouseworkMemo
	4,  // 21: shw.HouseworkService.GetHouseworkPoint:input_type -> shw.HouseworkPointRequest
	6,  // 22: shw.HouseworkService.GetHouseworkPointHistory:input_type -> shw.HouseworkPointHistoryRequest
	7,  // 23: shw.HouseworkService.GetHousework:output_type -> shw.HouseworkResponse
	8,  // 24: shw.HouseworkService.GetHouseworkDetail:output_type -> shw.HouseworkDetailResponse
	19, // 25: shw.HouseworkService.CreateHousework:output_type -> shw.CommonResponse
	19, // 26: shw.HouseworkService.UpdateHousework:output_type -> shw.CommonResponse
	19, // 27: shw.HouseworkService.FinishHousework:output_type -> shw.CommonResponse
	19, // 28: shw.HouseworkService.DeleteHousework:output_type -> shw.CommonResponse
	9,  // 29: shw.HouseworkService.GetHouseworkMemo:output_type -> shw.HouseworkMemoResponse
	19, // 30: shw.HouseworkService.CreateHouseworkMemo:output_type -> shw.CommonResponse
	19, // 31: shw.HouseworkService.UpdateHouseworkMemo:output_type -> shw.CommonResponse
	19, // 32: shw.HouseworkService.DeleteHouseworkMemo:output_type -> shw.CommonResponse
	10, // 33: shw.HouseworkService.GetHouseworkPoint:output_type -> shw.HouseworkPointResponse
	11, // 34: shw.HouseworkService.GetHouseworkPointHistory:output_type -> shw.HouseworkPointHistoryResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_housework_proto_init() }
func file_housework_proto_init() {
	if File_housework_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_housework_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkTargetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkMemoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPointHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkMemoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPointHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Housework); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkMemo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkPointHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_housework_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HouseworkTemplate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_housework_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_housework_proto_goTypes,
		DependencyIndexes: file_housework_proto_depIdxs,
		MessageInfos:      file_housework_proto_msgTypes,
	}.Build()
	File_housework_proto = out.File
	file_housework_proto_rawDesc = nil
	file_housework_proto_goTypes = nil
	file_housework_proto_depIdxs = nil
}
