// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: housework.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleRepeatType int32

const (
	ScheduleRepeatType_SCHEDULE_REPEAT_TYPE_UNSPECIFIED ScheduleRepeatType = 0
	ScheduleRepeatType_SCHEDULE_REPEAT_TYPE_WEEKLY      ScheduleRepeatType = 1
	ScheduleRepeatType_SCHEDULE_REPEAT_TYPE_MONTHLY     ScheduleRepeatType = 2
)

// Enum value maps for ScheduleRepeatType.
var (
	ScheduleRepeatType_name = map[int32]string{
		0: "SCHEDULE_REPEAT_TYPE_UNSPECIFIED",
		1: "SCHEDULE_REPEAT_TYPE_WEEKLY",
		2: "SCHEDULE_REPEAT_TYPE_MONTHLY",
	}
	ScheduleRepeatType_value = map[string]int32{
		"SCHEDULE_REPEAT_TYPE_UNSPECIFIED": 0,
		"SCHEDULE_REPEAT_TYPE_WEEKLY":      1,
		"SCHEDULE_REPEAT_TYPE_MONTHLY":     2,
	}
)

func (x ScheduleRepeatType) Enum() *ScheduleRepeatType {
	p := new(ScheduleRepeatType)
	*p = x
	return p
}

func (x ScheduleRepeatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleRepeatType) Descriptor() protoreflect.EnumDescriptor {
	return file_housework_proto_enumTypes[0].Descriptor()
}

func (ScheduleRepeatType) Type() protoreflect.EnumType {
	return &file_housework_proto_enumTypes[0]
}

func (x ScheduleRepeatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleRepeatType.Descriptor instead.
func (ScheduleRepeatType) EnumDescriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{0}
}

type ListHouseworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworksRequest) Reset() {
	*x = ListHouseworksRequest{}
	mi := &file_housework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworksRequest) ProtoMessage() {}

func (x *ListHouseworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworksRequest.ProtoReflect.Descriptor instead.
func (*ListHouseworksRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{0}
}

func (x *ListHouseworksRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListHouseworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Houseworks    []*Housework           `protobuf:"bytes,1,rep,name=houseworks,proto3" json:"houseworks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworksResponse) Reset() {
	*x = ListHouseworksResponse{}
	mi := &file_housework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworksResponse) ProtoMessage() {}

func (x *ListHouseworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworksResponse.ProtoReflect.Descriptor instead.
func (*ListHouseworksResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{1}
}

func (x *ListHouseworksResponse) GetHouseworks() []*Housework {
	if x != nil {
		return x.Houseworks
	}
	return nil
}

type GetHouseworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkRequest) Reset() {
	*x = GetHouseworkRequest{}
	mi := &file_housework_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkRequest) ProtoMessage() {}

func (x *GetHouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkRequest.ProtoReflect.Descriptor instead.
func (*GetHouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{2}
}

func (x *GetHouseworkRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHouseworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Housework     *Housework             `protobuf:"bytes,1,opt,name=housework,proto3" json:"housework,omitempty"`
	Memos         []*HouseworkMemo       `protobuf:"bytes,2,rep,name=memos,proto3" json:"memos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkResponse) Reset() {
	*x = GetHouseworkResponse{}
	mi := &file_housework_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkResponse) ProtoMessage() {}

func (x *GetHouseworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkResponse.ProtoReflect.Descriptor instead.
func (*GetHouseworkResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{3}
}

func (x *GetHouseworkResponse) GetHousework() *Housework {
	if x != nil {
		return x.Housework
	}
	return nil
}

func (x *GetHouseworkResponse) GetMemos() []*HouseworkMemo {
	if x != nil {
		return x.Memos
	}
	return nil
}

type CreateHouseworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Housework     *Housework             `protobuf:"bytes,1,opt,name=housework,proto3" json:"housework,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseworkRequest) Reset() {
	*x = CreateHouseworkRequest{}
	mi := &file_housework_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseworkRequest) ProtoMessage() {}

func (x *CreateHouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseworkRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHouseworkRequest) GetHousework() *Housework {
	if x != nil {
		return x.Housework
	}
	return nil
}

type UpdateHouseworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Housework     *Housework             `protobuf:"bytes,1,opt,name=housework,proto3" json:"housework,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseworkRequest) Reset() {
	*x = UpdateHouseworkRequest{}
	mi := &file_housework_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseworkRequest) ProtoMessage() {}

func (x *UpdateHouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHouseworkRequest) GetHousework() *Housework {
	if x != nil {
		return x.Housework
	}
	return nil
}

type FinishHouseworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishHouseworkRequest) Reset() {
	*x = FinishHouseworkRequest{}
	mi := &file_housework_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishHouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishHouseworkRequest) ProtoMessage() {}

func (x *FinishHouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishHouseworkRequest.ProtoReflect.Descriptor instead.
func (*FinishHouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{6}
}

func (x *FinishHouseworkRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteHouseworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseworkRequest) Reset() {
	*x = DeleteHouseworkRequest{}
	mi := &file_housework_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseworkRequest) ProtoMessage() {}

func (x *DeleteHouseworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteHouseworkRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteHouseworkRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListHouseworkMemosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseworkId   uint64                 `protobuf:"varint,1,opt,name=housework_id,json=houseworkId,proto3" json:"housework_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkMemosRequest) Reset() {
	*x = ListHouseworkMemosRequest{}
	mi := &file_housework_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkMemosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkMemosRequest) ProtoMessage() {}

func (x *ListHouseworkMemosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkMemosRequest.ProtoReflect.Descriptor instead.
func (*ListHouseworkMemosRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{8}
}

func (x *ListHouseworkMemosRequest) GetHouseworkId() uint64 {
	if x != nil {
		return x.HouseworkId
	}
	return 0
}

type ListHouseworkMemosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memos         []*HouseworkMemo       `protobuf:"bytes,1,rep,name=memos,proto3" json:"memos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkMemosResponse) Reset() {
	*x = ListHouseworkMemosResponse{}
	mi := &file_housework_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkMemosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkMemosResponse) ProtoMessage() {}

func (x *ListHouseworkMemosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkMemosResponse.ProtoReflect.Descriptor instead.
func (*ListHouseworkMemosResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{9}
}

func (x *ListHouseworkMemosResponse) GetMemos() []*HouseworkMemo {
	if x != nil {
		return x.Memos
	}
	return nil
}

type CreateHouseworkMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *HouseworkMemo         `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseworkMemoRequest) Reset() {
	*x = CreateHouseworkMemoRequest{}
	mi := &file_housework_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseworkMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseworkMemoRequest) ProtoMessage() {}

func (x *CreateHouseworkMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseworkMemoRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseworkMemoRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{10}
}

func (x *CreateHouseworkMemoRequest) GetMemo() *HouseworkMemo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type UpdateHouseworkMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *HouseworkMemo         `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseworkMemoRequest) Reset() {
	*x = UpdateHouseworkMemoRequest{}
	mi := &file_housework_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseworkMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseworkMemoRequest) ProtoMessage() {}

func (x *UpdateHouseworkMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseworkMemoRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseworkMemoRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateHouseworkMemoRequest) GetMemo() *HouseworkMemo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type DeleteHouseworkMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseworkMemoRequest) Reset() {
	*x = DeleteHouseworkMemoRequest{}
	mi := &file_housework_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseworkMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseworkMemoRequest) ProtoMessage() {}

func (x *DeleteHouseworkMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseworkMemoRequest.ProtoReflect.Descriptor instead.
func (*DeleteHouseworkMemoRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteHouseworkMemoRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHouseworkPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkPointRequest) Reset() {
	*x = GetHouseworkPointRequest{}
	mi := &file_housework_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkPointRequest) ProtoMessage() {}

func (x *GetHouseworkPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkPointRequest.ProtoReflect.Descriptor instead.
func (*GetHouseworkPointRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{13}
}

func (x *GetHouseworkPointRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetHouseworkPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *HouseworkPoint        `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkPointResponse) Reset() {
	*x = GetHouseworkPointResponse{}
	mi := &file_housework_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkPointResponse) ProtoMessage() {}

func (x *GetHouseworkPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkPointResponse.ProtoReflect.Descriptor instead.
func (*GetHouseworkPointResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{14}
}

func (x *GetHouseworkPointResponse) GetPoint() *HouseworkPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type ListHouseworkPointHistoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkPointHistoriesRequest) Reset() {
	*x = ListHouseworkPointHistoriesRequest{}
	mi := &file_housework_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkPointHistoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkPointHistoriesRequest) ProtoMessage() {}

func (x *ListHouseworkPointHistoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkPointHistoriesRequest.ProtoReflect.Descriptor instead.
func (*ListHouseworkPointHistoriesRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{15}
}

func (x *ListHouseworkPointHistoriesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListHouseworkPointHistoriesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Histories     []*HouseworkPointHistory `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkPointHistoriesResponse) Reset() {
	*x = ListHouseworkPointHistoriesResponse{}
	mi := &file_housework_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkPointHistoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkPointHistoriesResponse) ProtoMessage() {}

func (x *ListHouseworkPointHistoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkPointHistoriesResponse.ProtoReflect.Descriptor instead.
func (*ListHouseworkPointHistoriesResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{16}
}

func (x *ListHouseworkPointHistoriesResponse) GetHistories() []*HouseworkPointHistory {
	if x != nil {
		return x.Histories
	}
	return nil
}

type GetHouseworkTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkTemplateRequest) Reset() {
	*x = GetHouseworkTemplateRequest{}
	mi := &file_housework_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkTemplateRequest) ProtoMessage() {}

func (x *GetHouseworkTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetHouseworkTemplateRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{17}
}

func (x *GetHouseworkTemplateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHouseworkTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *HouseworkTemplate     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkTemplateResponse) Reset() {
	*x = GetHouseworkTemplateResponse{}
	mi := &file_housework_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkTemplateResponse) ProtoMessage() {}

func (x *GetHouseworkTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetHouseworkTemplateResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{18}
}

func (x *GetHouseworkTemplateResponse) GetTemplate() *HouseworkTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListHouseworkTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkTemplatesRequest) Reset() {
	*x = ListHouseworkTemplatesRequest{}
	mi := &file_housework_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkTemplatesRequest) ProtoMessage() {}

func (x *ListHouseworkTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListHouseworkTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{19}
}

func (x *ListHouseworkTemplatesRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListHouseworkTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*HouseworkTemplate   `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkTemplatesResponse) Reset() {
	*x = ListHouseworkTemplatesResponse{}
	mi := &file_housework_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkTemplatesResponse) ProtoMessage() {}

func (x *ListHouseworkTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListHouseworkTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{20}
}

func (x *ListHouseworkTemplatesResponse) GetTemplates() []*HouseworkTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateHouseworkTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *HouseworkTemplate     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseworkTemplateRequest) Reset() {
	*x = CreateHouseworkTemplateRequest{}
	mi := &file_housework_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseworkTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseworkTemplateRequest) ProtoMessage() {}

func (x *CreateHouseworkTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseworkTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseworkTemplateRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{21}
}

func (x *CreateHouseworkTemplateRequest) GetTemplate() *HouseworkTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateHouseworkTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *HouseworkTemplate     `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseworkTemplateRequest) Reset() {
	*x = UpdateHouseworkTemplateRequest{}
	mi := &file_housework_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseworkTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseworkTemplateRequest) ProtoMessage() {}

func (x *UpdateHouseworkTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseworkTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseworkTemplateRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateHouseworkTemplateRequest) GetTemplate() *HouseworkTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type DeleteHouseworkTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseworkTemplateRequest) Reset() {
	*x = DeleteHouseworkTemplateRequest{}
	mi := &file_housework_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseworkTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseworkTemplateRequest) ProtoMessage() {}

func (x *DeleteHouseworkTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseworkTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteHouseworkTemplateRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteHouseworkTemplateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHouseworkScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkScheduleRequest) Reset() {
	*x = GetHouseworkScheduleRequest{}
	mi := &file_housework_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkScheduleRequest) ProtoMessage() {}

func (x *GetHouseworkScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetHouseworkScheduleRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{24}
}

func (x *GetHouseworkScheduleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHouseworkScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *HouseworkSchedule     `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHouseworkScheduleResponse) Reset() {
	*x = GetHouseworkScheduleResponse{}
	mi := &file_housework_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHouseworkScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHouseworkScheduleResponse) ProtoMessage() {}

func (x *GetHouseworkScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHouseworkScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetHouseworkScheduleResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{25}
}

func (x *GetHouseworkScheduleResponse) GetSchedule() *HouseworkSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ListHouseworkSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkSchedulesRequest) Reset() {
	*x = ListHouseworkSchedulesRequest{}
	mi := &file_housework_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkSchedulesRequest) ProtoMessage() {}

func (x *ListHouseworkSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListHouseworkSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{26}
}

func (x *ListHouseworkSchedulesRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListHouseworkSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*HouseworkSchedule   `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseworkSchedulesResponse) Reset() {
	*x = ListHouseworkSchedulesResponse{}
	mi := &file_housework_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseworkSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseworkSchedulesResponse) ProtoMessage() {}

func (x *ListHouseworkSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseworkSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListHouseworkSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{27}
}

func (x *ListHouseworkSchedulesResponse) GetSchedules() []*HouseworkSchedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type CreateHouseworkScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *HouseworkSchedule     `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseworkScheduleRequest) Reset() {
	*x = CreateHouseworkScheduleRequest{}
	mi := &file_housework_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseworkScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseworkScheduleRequest) ProtoMessage() {}

func (x *CreateHouseworkScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseworkScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseworkScheduleRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{28}
}

func (x *CreateHouseworkScheduleRequest) GetSchedule() *HouseworkSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type UpdateHouseworkScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *HouseworkSchedule     `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHouseworkScheduleRequest) Reset() {
	*x = UpdateHouseworkScheduleRequest{}
	mi := &file_housework_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHouseworkScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHouseworkScheduleRequest) ProtoMessage() {}

func (x *UpdateHouseworkScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHouseworkScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateHouseworkScheduleRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateHouseworkScheduleRequest) GetSchedule() *HouseworkSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type DeleteHouseworkScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHouseworkScheduleRequest) Reset() {
	*x = DeleteHouseworkScheduleRequest{}
	mi := &file_housework_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHouseworkScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHouseworkScheduleRequest) ProtoMessage() {}

func (x *DeleteHouseworkScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHouseworkScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteHouseworkScheduleRequest) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteHouseworkScheduleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Housework struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	StatusId      uint64                 `protobuf:"varint,5,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	WorkUser      *UserInfo              `protobuf:"bytes,6,opt,name=work_user,json=workUser,proto3" json:"work_user,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Housework) Reset() {
	*x = Housework{}
	mi := &file_housework_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Housework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Housework) ProtoMessage() {}

func (x *Housework) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Housework.ProtoReflect.Descriptor instead.
func (*Housework) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{31}
}

func (x *Housework) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Housework) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *Housework) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Housework) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Housework) GetStatusId() uint64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *Housework) GetWorkUser() *UserInfo {
	if x != nil {
		return x.WorkUser
	}
	return nil
}

func (x *Housework) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Housework) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type HouseworkMemo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HouseworkId   uint64                 `protobuf:"varint,2,opt,name=housework_id,json=houseworkId,proto3" json:"housework_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SendFrom      *UserInfo              `protobuf:"bytes,4,opt,name=send_from,json=sendFrom,proto3" json:"send_from,omitempty"`
	StartedAt     int64                  `protobuf:"varint,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseworkMemo) Reset() {
	*x = HouseworkMemo{}
	mi := &file_housework_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseworkMemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkMemo) ProtoMessage() {}

func (x *HouseworkMemo) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkMemo.ProtoReflect.Descriptor instead.
func (*HouseworkMemo) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{32}
}

func (x *HouseworkMemo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkMemo) GetHouseworkId() uint64 {
	if x != nil {
		return x.HouseworkId
	}
	return 0
}

func (x *HouseworkMemo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HouseworkMemo) GetSendFrom() *UserInfo {
	if x != nil {
		return x.SendFrom
	}
	return nil
}

func (x *HouseworkMemo) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *HouseworkMemo) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *HouseworkMemo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkMemo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Point         int64                  `protobuf:"varint,3,opt,name=point,proto3" json:"point,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseworkPoint) Reset() {
	*x = HouseworkPoint{}
	mi := &file_housework_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseworkPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPoint) ProtoMessage() {}

func (x *HouseworkPoint) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPoint.ProtoReflect.Descriptor instead.
func (*HouseworkPoint) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{33}
}

func (x *HouseworkPoint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkPoint) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HouseworkPoint) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *HouseworkPoint) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkPoint) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkPointHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *UserInfo              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Point         int64                  `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseworkPointHistory) Reset() {
	*x = HouseworkPointHistory{}
	mi := &file_housework_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseworkPointHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkPointHistory) ProtoMessage() {}

func (x *HouseworkPointHistory) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkPointHistory.ProtoReflect.Descriptor instead.
func (*HouseworkPointHistory) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{34}
}

func (x *HouseworkPointHistory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkPointHistory) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *HouseworkPointHistory) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HouseworkPointHistory) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *HouseworkPointHistory) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkPointHistory) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseworkTemplate) Reset() {
	*x = HouseworkTemplate{}
	mi := &file_housework_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseworkTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkTemplate) ProtoMessage() {}

func (x *HouseworkTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkTemplate.ProtoReflect.Descriptor instead.
func (*HouseworkTemplate) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{35}
}

func (x *HouseworkTemplate) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkTemplate) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *HouseworkTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseworkTemplate) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HouseworkTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type HouseworkSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,2,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Assignee      *UserInfo              `protobuf:"bytes,5,opt,name=assignee,proto3" json:"assignee,omitempty"`
	DueAt         int64                  `protobuf:"varint,6,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	Repeat        *ScheduleRepeat        `protobuf:"bytes,7,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Reminders     []*ScheduleReminder    `protobuf:"bytes,8,rep,name=reminders,proto3" json:"reminders,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseworkSchedule) Reset() {
	*x = HouseworkSchedule{}
	mi := &file_housework_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseworkSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseworkSchedule) ProtoMessage() {}

func (x *HouseworkSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseworkSchedule.ProtoReflect.Descriptor instead.
func (*HouseworkSchedule) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{36}
}

func (x *HouseworkSchedule) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseworkSchedule) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

func (x *HouseworkSchedule) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HouseworkSchedule) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *HouseworkSchedule) GetAssignee() *UserInfo {
	if x != nil {
		return x.Assignee
	}
	return nil
}

func (x *HouseworkSchedule) GetDueAt() int64 {
	if x != nil {
		return x.DueAt
	}
	return 0
}

func (x *HouseworkSchedule) GetRepeat() *ScheduleRepeat {
	if x != nil {
		return x.Repeat
	}
	return nil
}

func (x *HouseworkSchedule) GetReminders() []*ScheduleReminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

func (x *HouseworkSchedule) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HouseworkSchedule) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ScheduleRepeat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           ScheduleRepeatType     `protobuf:"varint,1,opt,name=type,proto3,enum=shw.ScheduleRepeatType" json:"type,omitempty"`
	Weekdays       []int32                `protobuf:"varint,2,rep,packed,name=weekdays,proto3" json:"weekdays,omitempty"`                                     // 0-6 or 1-7 どっちかに統一推奨
	WeekOfMonth    []int32                `protobuf:"varint,3,rep,packed,name=week_of_month,json=weekOfMonth,proto3" json:"week_of_month,omitempty"`          // 例: 1-5
	WeekdayInMonth []int32                `protobuf:"varint,4,rep,packed,name=weekday_in_month,json=weekdayInMonth,proto3" json:"weekday_in_month,omitempty"` // 例: 第X週の何曜日
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleRepeat) Reset() {
	*x = ScheduleRepeat{}
	mi := &file_housework_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRepeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRepeat) ProtoMessage() {}

func (x *ScheduleRepeat) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRepeat.ProtoReflect.Descriptor instead.
func (*ScheduleRepeat) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{37}
}

func (x *ScheduleRepeat) GetType() ScheduleRepeatType {
	if x != nil {
		return x.Type
	}
	return ScheduleRepeatType_SCHEDULE_REPEAT_TYPE_UNSPECIFIED
}

func (x *ScheduleRepeat) GetWeekdays() []int32 {
	if x != nil {
		return x.Weekdays
	}
	return nil
}

func (x *ScheduleRepeat) GetWeekOfMonth() []int32 {
	if x != nil {
		return x.WeekOfMonth
	}
	return nil
}

func (x *ScheduleRepeat) GetWeekdayInMonth() []int32 {
	if x != nil {
		return x.WeekdayInMonth
	}
	return nil
}

type ScheduleReminder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinutesBefore int32                  `protobuf:"varint,1,opt,name=minutes_before,json=minutesBefore,proto3" json:"minutes_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleReminder) Reset() {
	*x = ScheduleReminder{}
	mi := &file_housework_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleReminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleReminder) ProtoMessage() {}

func (x *ScheduleReminder) ProtoReflect() protoreflect.Message {
	mi := &file_housework_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleReminder.ProtoReflect.Descriptor instead.
func (*ScheduleReminder) Descriptor() ([]byte, []int) {
	return file_housework_proto_rawDescGZIP(), []int{38}
}

func (x *ScheduleReminder) GetMinutesBefore() int32 {
	if x != nil {
		return x.MinutesBefore
	}
	return 0
}

var File_housework_proto protoreflect.FileDescriptor

const file_housework_proto_rawDesc = "" +
	"\n" +
	"\x0fhousework.proto\x12\x03shw\x1a\fcommon.proto\"4\n" +
	"\x15ListHouseworksRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"H\n" +
	"\x16ListHouseworksResponse\x12.\n" +
	"\n" +
	"houseworks\x18\x01 \x03(\v2\x0e.shw.HouseworkR\n" +
	"houseworks\"%\n" +
	"\x13GetHouseworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"n\n" +
	"\x14GetHouseworkResponse\x12,\n" +
	"\thousework\x18\x01 \x01(\v2\x0e.shw.HouseworkR\thousework\x12(\n" +
	"\x05memos\x18\x02 \x03(\v2\x12.shw.HouseworkMemoR\x05memos\"F\n" +
	"\x16CreateHouseworkRequest\x12,\n" +
	"\thousework\x18\x01 \x01(\v2\x0e.shw.HouseworkR\thousework\"F\n" +
	"\x16UpdateHouseworkRequest\x12,\n" +
	"\thousework\x18\x01 \x01(\v2\x0e.shw.HouseworkR\thousework\"(\n" +
	"\x16FinishHouseworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"(\n" +
	"\x16DeleteHouseworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\">\n" +
	"\x19ListHouseworkMemosRequest\x12!\n" +
	"\fhousework_id\x18\x01 \x01(\x04R\vhouseworkId\"F\n" +
	"\x1aListHouseworkMemosResponse\x12(\n" +
	"\x05memos\x18\x01 \x03(\v2\x12.shw.HouseworkMemoR\x05memos\"D\n" +
	"\x1aCreateHouseworkMemoRequest\x12&\n" +
	"\x04memo\x18\x01 \x01(\v2\x12.shw.HouseworkMemoR\x04memo\"D\n" +
	"\x1aUpdateHouseworkMemoRequest\x12&\n" +
	"\x04memo\x18\x01 \x01(\v2\x12.shw.HouseworkMemoR\x04memo\",\n" +
	"\x1aDeleteHouseworkMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"3\n" +
	"\x18GetHouseworkPointRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"F\n" +
	"\x19GetHouseworkPointResponse\x12)\n" +
	"\x05point\x18\x01 \x01(\v2\x13.shw.HouseworkPointR\x05point\"=\n" +
	"\"ListHouseworkPointHistoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"_\n" +
	"#ListHouseworkPointHistoriesResponse\x128\n" +
	"\thistories\x18\x01 \x03(\v2\x1a.shw.HouseworkPointHistoryR\thistories\"-\n" +
	"\x1bGetHouseworkTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"R\n" +
	"\x1cGetHouseworkTemplateResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.shw.HouseworkTemplateR\btemplate\"<\n" +
	"\x1dListHouseworkTemplatesRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"V\n" +
	"\x1eListHouseworkTemplatesResponse\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.shw.HouseworkTemplateR\ttemplates\"T\n" +
	"\x1eCreateHouseworkTemplateRequest\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.shw.HouseworkTemplateR\btemplate\"T\n" +
	"\x1eUpdateHouseworkTemplateRequest\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.shw.HouseworkTemplateR\btemplate\"0\n" +
	"\x1eDeleteHouseworkTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"-\n" +
	"\x1bGetHouseworkScheduleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"R\n" +
	"\x1cGetHouseworkScheduleResponse\x122\n" +
	"\bschedule\x18\x01 \x01(\v2\x16.shw.HouseworkScheduleR\bschedule\"<\n" +
	"\x1dListHouseworkSchedulesRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"V\n" +
	"\x1eListHouseworkSchedulesResponse\x124\n" +
	"\tschedules\x18\x01 \x03(\v2\x16.shw.HouseworkScheduleR\tschedules\"T\n" +
	"\x1eCreateHouseworkScheduleRequest\x122\n" +
	"\bschedule\x18\x01 \x01(\v2\x16.shw.HouseworkScheduleR\bschedule\"T\n" +
	"\x1eUpdateHouseworkScheduleRequest\x122\n" +
	"\bschedule\x18\x01 \x01(\v2\x16.shw.HouseworkScheduleR\bschedule\"0\n" +
	"\x1eDeleteHouseworkScheduleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xe9\x01\n" +
	"\tHousework\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\x04R\bfamilyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1b\n" +
	"\tstatus_id\x18\x05 \x01(\x04R\bstatusId\x12*\n" +
	"\twork_user\x18\x06 \x01(\v2\r.shw.UserInfoR\bworkUser\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\b \x01(\x03R\aendedAt\"\x80\x02\n" +
	"\rHouseworkMemo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fhousework_id\x18\x02 \x01(\x04R\vhouseworkId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\tsend_from\x18\x04 \x01(\v2\r.shw.UserInfoR\bsendFrom\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x06 \x01(\x03R\aendedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\x97\x01\n" +
	"\x0eHouseworkPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.shw.UserInfoR\x04user\x12\x14\n" +
	"\x05point\x18\x03 \x01(\x03R\x05point\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xb6\x01\n" +
	"\x15HouseworkPointHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\x04user\x18\x02 \x01(\v2\r.shw.UserInfoR\x04user\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x14\n" +
	"\x05point\x18\x04 \x01(\x03R\x05point\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xac\x01\n" +
	"\x11HouseworkTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\x04R\bfamilyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\xd0\x02\n" +
	"\x11HouseworkSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfamily_id\x18\x02 \x01(\x04R\bfamilyId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12)\n" +
	"\bassignee\x18\x05 \x01(\v2\r.shw.UserInfoR\bassignee\x12\x15\n" +
	"\x06due_at\x18\x06 \x01(\x03R\x05dueAt\x12+\n" +
	"\x06repeat\x18\a \x01(\v2\x13.shw.ScheduleRepeatR\x06repeat\x123\n" +
	"\treminders\x18\b \x03(\v2\x15.shw.ScheduleReminderR\treminders\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xa7\x01\n" +
	"\x0eScheduleRepeat\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.shw.ScheduleRepeatTypeR\x04type\x12\x1a\n" +
	"\bweekdays\x18\x02 \x03(\x05R\bweekdays\x12\"\n" +
	"\rweek_of_month\x18\x03 \x03(\x05R\vweekOfMonth\x12(\n" +
	"\x10weekday_in_month\x18\x04 \x03(\x05R\x0eweekdayInMonth\"9\n" +
	"\x10ScheduleReminder\x12%\n" +
	"\x0eminutes_before\x18\x01 \x01(\x05R\rminutesBefore*}\n" +
	"\x12ScheduleRepeatType\x12$\n" +
	" SCHEDULE_REPEAT_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSCHEDULE_REPEAT_TYPE_WEEKLY\x10\x01\x12 \n" +
	"\x1cSCHEDULE_REPEAT_TYPE_MONTHLY\x10\x022\xc2\x03\n" +
	"\x10HouseworkService\x12K\n" +
	"\x0eListHouseworks\x12\x1a.shw.ListHouseworksRequest\x1a\x1b.shw.ListHouseworksResponse\"\x00\x12E\n" +
	"\fGetHousework\x12\x18.shw.GetHouseworkRequest\x1a\x19.shw.GetHouseworkResponse\"\x00\x12E\n" +
	"\x0fCreateHousework\x12\x1b.shw.CreateHouseworkRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fUpdateHousework\x12\x1b.shw.UpdateHouseworkRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fFinishHousework\x12\x1b.shw.FinishHouseworkRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fDeleteHousework\x12\x1b.shw.DeleteHouseworkRequest\x1a\x13.shw.CommonResponse\"\x002\xdc\x02\n" +
	"\x14HouseworkMemoService\x12W\n" +
	"\x12ListHouseworkMemos\x12\x1e.shw.ListHouseworkMemosRequest\x1a\x1f.shw.ListHouseworkMemosResponse\"\x00\x12M\n" +
	"\x13CreateHouseworkMemo\x12\x1f.shw.CreateHouseworkMemoRequest\x1a\x13.shw.CommonResponse\"\x00\x12M\n" +
	"\x13UpdateHouseworkMemo\x12\x1f.shw.UpdateHouseworkMemoRequest\x1a\x13.shw.CommonResponse\"\x00\x12M\n" +
	"\x13DeleteHouseworkMemo\x12\x1f.shw.DeleteHouseworkMemoRequest\x1a\x13.shw.CommonResponse\"\x002\xe1\x01\n" +
	"\x15HouseworkPointService\x12T\n" +
	"\x11GetHouseworkPoint\x12\x1d.shw.GetHouseworkPointRequest\x1a\x1e.shw.GetHouseworkPointResponse\"\x00\x12r\n" +
	"\x1bListHouseworkPointHistories\x12'.shw.ListHouseworkPointHistoriesRequest\x1a(.shw.ListHouseworkPointHistoriesResponse\"\x002\xe3\x03\n" +
	"\x18HouseworkTemplateService\x12]\n" +
	"\x14GetHouseworkTemplate\x12 .shw.GetHouseworkTemplateRequest\x1a!.shw.GetHouseworkTemplateResponse\"\x00\x12c\n" +
	"\x16ListHouseworkTemplates\x12\".shw.ListHouseworkTemplatesRequest\x1a#.shw.ListHouseworkTemplatesResponse\"\x00\x12U\n" +
	"\x17CreateHouseworkTemplate\x12#.shw.CreateHouseworkTemplateRequest\x1a\x13.shw.CommonResponse\"\x00\x12U\n" +
	"\x17UpdateHouseworkTemplate\x12#.shw.UpdateHouseworkTemplateRequest\x1a\x13.shw.CommonResponse\"\x00\x12U\n" +
	"\x17DeleteHouseworkTemplate\x12#.shw.DeleteHouseworkTemplateRequest\x1a\x13.shw.CommonResponse\"\x002\xe3\x03\n" +
	"\x18HouseworkScheduleService\x12]\n" +
	"\x14GetHouseworkSchedule\x12 .shw.GetHouseworkScheduleRequest\x1a!.shw.GetHouseworkScheduleResponse\"\x00\x12c\n" +
	"\x16ListHouseworkSchedules\x12\".shw.ListHouseworkSchedulesRequest\x1a#.shw.ListHouseworkSchedulesResponse\"\x00\x12U\n" +
	"\x17CreateHouseworkSchedule\x12#.shw.CreateHouseworkScheduleRequest\x1a\x13.shw.CommonResponse\"\x00\x12U\n" +
	"\x17UpdateHouseworkSchedule\x12#.shw.UpdateHouseworkScheduleRequest\x1a\x13.shw.CommonResponse\"\x00\x12U\n" +
	"\x17DeleteHouseworkSchedule\x12#.shw.DeleteHouseworkScheduleRequest\x1a\x13.shw.CommonResponse\"\x00B\x12Z\x10shwgrpc/pkg/grpcb\x06proto3"

var (
	file_housework_proto_rawDescOnce sync.Once
	file_housework_proto_rawDescData []byte
)

func file_housework_proto_rawDescGZIP() []byte {
	file_housework_proto_rawDescOnce.Do(func() {
		file_housework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_housework_proto_rawDesc), len(file_housework_proto_rawDesc)))
	})
	return file_housework_proto_rawDescData
}

var file_housework_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_housework_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_housework_proto_goTypes = []any{
	(ScheduleRepeatType)(0),                     // 0: shw.ScheduleRepeatType
	(*ListHouseworksRequest)(nil),               // 1: shw.ListHouseworksRequest
	(*ListHouseworksResponse)(nil),              // 2: shw.ListHouseworksResponse
	(*GetHouseworkRequest)(nil),                 // 3: shw.GetHouseworkRequest
	(*GetHouseworkResponse)(nil),                // 4: shw.GetHouseworkResponse
	(*CreateHouseworkRequest)(nil),              // 5: shw.CreateHouseworkRequest
	(*UpdateHouseworkRequest)(nil),              // 6: shw.UpdateHouseworkRequest
	(*FinishHouseworkRequest)(nil),              // 7: shw.FinishHouseworkRequest
	(*DeleteHouseworkRequest)(nil),              // 8: shw.DeleteHouseworkRequest
	(*ListHouseworkMemosRequest)(nil),           // 9: shw.ListHouseworkMemosRequest
	(*ListHouseworkMemosResponse)(nil),          // 10: shw.ListHouseworkMemosResponse
	(*CreateHouseworkMemoRequest)(nil),          // 11: shw.CreateHouseworkMemoRequest
	(*UpdateHouseworkMemoRequest)(nil),          // 12: shw.UpdateHouseworkMemoRequest
	(*DeleteHouseworkMemoRequest)(nil),          // 13: shw.DeleteHouseworkMemoRequest
	(*GetHouseworkPointRequest)(nil),            // 14: shw.GetHouseworkPointRequest
	(*GetHouseworkPointResponse)(nil),           // 15: shw.GetHouseworkPointResponse
	(*ListHouseworkPointHistoriesRequest)(nil),  // 16: shw.ListHouseworkPointHistoriesRequest
	(*ListHouseworkPointHistoriesResponse)(nil), // 17: shw.ListHouseworkPointHistoriesResponse
	(*GetHouseworkTemplateRequest)(nil),         // 18: shw.GetHouseworkTemplateRequest
	(*GetHouseworkTemplateResponse)(nil),        // 19: shw.GetHouseworkTemplateResponse
	(*ListHouseworkTemplatesRequest)(nil),       // 20: shw.ListHouseworkTemplatesRequest
	(*ListHouseworkTemplatesResponse)(nil),      // 21: shw.ListHouseworkTemplatesResponse
	(*CreateHouseworkTemplateRequest)(nil),      // 22: shw.CreateHouseworkTemplateRequest
	(*UpdateHouseworkTemplateRequest)(nil),      // 23: shw.UpdateHouseworkTemplateRequest
	(*DeleteHouseworkTemplateRequest)(nil),      // 24: shw.DeleteHouseworkTemplateRequest
	(*GetHouseworkScheduleRequest)(nil),         // 25: shw.GetHouseworkScheduleRequest
	(*GetHouseworkScheduleResponse)(nil),        // 26: shw.GetHouseworkScheduleResponse
	(*ListHouseworkSchedulesRequest)(nil),       // 27: shw.ListHouseworkSchedulesRequest
	(*ListHouseworkSchedulesResponse)(nil),      // 28: shw.ListHouseworkSchedulesResponse
	(*CreateHouseworkScheduleRequest)(nil),      // 29: shw.CreateHouseworkScheduleRequest
	(*UpdateHouseworkScheduleRequest)(nil),      // 30: shw.UpdateHouseworkScheduleRequest
	(*DeleteHouseworkScheduleRequest)(nil),      // 31: shw.DeleteHouseworkScheduleRequest
	(*Housework)(nil),                           // 32: shw.Housework
	(*HouseworkMemo)(nil),                       // 33: shw.HouseworkMemo
	(*HouseworkPoint)(nil),                      // 34: shw.HouseworkPoint
	(*HouseworkPointHistory)(nil),               // 35: shw.HouseworkPointHistory
	(*HouseworkTemplate)(nil),                   // 36: shw.HouseworkTemplate
	(*HouseworkSchedule)(nil),                   // 37: shw.HouseworkSchedule
	(*ScheduleRepeat)(nil),                      // 38: shw.ScheduleRepeat
	(*ScheduleReminder)(nil),                    // 39: shw.ScheduleReminder
	(*UserInfo)(nil),                            // 40: shw.UserInfo
	(*CommonResponse)(nil),                      // 41: shw.CommonResponse
}
var file_housework_proto_depIdxs = []int32{
	32, // 0: shw.ListHouseworksResponse.houseworks:type_name -> shw.Housework
	32, // 1: shw.GetHouseworkResponse.housework:type_name -> shw.Housework
	33, // 2: shw.GetHouseworkResponse.memos:type_name -> shw.HouseworkMemo
	32, // 3: shw.CreateHouseworkRequest.housework:type_name -> shw.Housework
	32, // 4: shw.UpdateHouseworkRequest.housework:type_name -> shw.Housework
	33, // 5: shw.ListHouseworkMemosResponse.memos:type_name -> shw.HouseworkMemo
	33, // 6: shw.CreateHouseworkMemoRequest.memo:type_name -> shw.HouseworkMemo
	33, // 7: shw.UpdateHouseworkMemoRequest.memo:type_name -> shw.HouseworkMemo
	34, // 8: shw.GetHouseworkPointResponse.point:type_name -> shw.HouseworkPoint
	35, // 9: shw.ListHouseworkPointHistoriesResponse.histories:type_name -> shw.HouseworkPointHistory
	36, // 10: shw.GetHouseworkTemplateResponse.template:type_name -> shw.HouseworkTemplate
	36, // 11: shw.ListHouseworkTemplatesResponse.templates:type_name -> shw.HouseworkTemplate
	36, // 12: shw.CreateHouseworkTemplateRequest.template:type_name -> shw.HouseworkTemplate
	36, // 13: shw.UpdateHouseworkTemplateRequest.template:type_name -> shw.HouseworkTemplate
	37, // 14: shw.GetHouseworkScheduleResponse.schedule:type_name -> shw.HouseworkSchedule
	37, // 15: shw.ListHouseworkSchedulesResponse.schedules:type_name -> shw.HouseworkSchedule
	37, // 16: shw.CreateHouseworkScheduleRequest.schedule:type_name -> shw.HouseworkSchedule
	37, // 17: shw.UpdateHouseworkScheduleRequest.schedule:type_name -> shw.HouseworkSchedule
	40, // 18: shw.Housework.work_user:type_name -> shw.UserInfo
	40, // 19: shw.HouseworkMemo.send_from:type_name -> shw.UserInfo
	40, // 20: shw.HouseworkPoint.user:type_name -> shw.UserInfo
	40, // 21: shw.HouseworkPointHistory.user:type_name -> shw.UserInfo
	40, // 22: shw.HouseworkSchedule.assignee:type_name -> shw.UserInfo
	38, // 23: shw.HouseworkSchedule.repeat:type_name -> shw.ScheduleRepeat
	39, // 24: shw.HouseworkSchedule.reminders:type_name -> shw.ScheduleReminder
	0,  // 25: shw.ScheduleRepeat.type:type_name -> shw.ScheduleRepeatType
	1,  // 26: shw.HouseworkService.ListHouseworks:input_type -> shw.ListHouseworksRequest
	3,  // 27: shw.HouseworkService.GetHousework:input_type -> shw.GetHouseworkRequest
	5,  // 28: shw.HouseworkService.CreateHousework:input_type -> shw.CreateHouseworkRequest
	6,  // 29: shw.HouseworkService.UpdateHousework:input_type -> shw.UpdateHouseworkRequest
	7,  // 30: shw.HouseworkService.FinishHousework:input_type -> shw.FinishHouseworkRequest
	8,  // 31: shw.HouseworkService.DeleteHousework:input_type -> shw.DeleteHouseworkRequest
	9,  // 32: shw.HouseworkMemoService.ListHouseworkMemos:input_type -> shw.ListHouseworkMemosRequest
	11, // 33: shw.HouseworkMemoService.CreateHouseworkMemo:input_type -> shw.CreateHouseworkMemoRequest
	12, // 34: shw.HouseworkMemoService.UpdateHouseworkMemo:input_type -> shw.UpdateHouseworkMemoRequest
	13, // 35: shw.HouseworkMemoService.DeleteHouseworkMemo:input_type -> shw.DeleteHouseworkMemoRequest
	14, // 36: shw.HouseworkPointService.GetHouseworkPoint:input_type -> shw.GetHouseworkPointRequest
	16, // 37: shw.HouseworkPointService.ListHouseworkPointHistories:input_type -> shw.ListHouseworkPointHistoriesRequest
	18, // 38: shw.HouseworkTemplateService.GetHouseworkTemplate:input_type -> shw.GetHouseworkTemplateRequest
	20, // 39: shw.HouseworkTemplateService.ListHouseworkTemplates:input_type -> shw.ListHouseworkTemplatesRequest
	22, // 40: shw.HouseworkTemplateService.CreateHouseworkTemplate:input_type -> shw.CreateHouseworkTemplateRequest
	23, // 41: shw.HouseworkTemplateService.UpdateHouseworkTemplate:input_type -> shw.UpdateHouseworkTemplateRequest
	24, // 42: shw.HouseworkTemplateService.DeleteHouseworkTemplate:input_type -> shw.DeleteHouseworkTemplateRequest
	25, // 43: shw.HouseworkScheduleService.GetHouseworkSchedule:input_type -> shw.GetHouseworkScheduleRequest
	27, // 44: shw.HouseworkScheduleService.ListHouseworkSchedules:input_type -> shw.ListHouseworkSchedulesRequest
	29, // 45: shw.HouseworkScheduleService.CreateHouseworkSchedule:input_type -> shw.CreateHouseworkScheduleRequest
	30, // 46: shw.HouseworkScheduleService.UpdateHouseworkSchedule:input_type -> shw.UpdateHouseworkScheduleRequest
	31, // 47: shw.HouseworkScheduleService.DeleteHouseworkSchedule:input_type -> shw.DeleteHouseworkScheduleRequest
	2,  // 48: shw.HouseworkService.ListHouseworks:output_type -> shw.ListHouseworksResponse
	4,  // 49: shw.HouseworkService.GetHousework:output_type -> shw.GetHouseworkResponse
	41, // 50: shw.HouseworkService.CreateHousework:output_type -> shw.CommonResponse
	41, // 51: shw.HouseworkService.UpdateHousework:output_type -> shw.CommonResponse
	41, // 52: shw.HouseworkService.FinishHousework:output_type -> shw.CommonResponse
	41, // 53: shw.HouseworkService.DeleteHousework:output_type -> shw.CommonResponse
	10, // 54: shw.HouseworkMemoService.ListHouseworkMemos:output_type -> shw.ListHouseworkMemosResponse
	41, // 55: shw.HouseworkMemoService.CreateHouseworkMemo:output_type -> shw.CommonResponse
	41, // 56: shw.HouseworkMemoService.UpdateHouseworkMemo:output_type -> shw.CommonResponse
	41, // 57: shw.HouseworkMemoService.DeleteHouseworkMemo:output_type -> shw.CommonResponse
	15, // 58: shw.HouseworkPointService.GetHouseworkPoint:output_type -> shw.GetHouseworkPointResponse
	17, // 59: shw.HouseworkPointService.ListHouseworkPointHistories:output_type -> shw.ListHouseworkPointHistoriesResponse
	19, // 60: shw.HouseworkTemplateService.GetHouseworkTemplate:output_type -> shw.GetHouseworkTemplateResponse
	21, // 61: shw.HouseworkTemplateService.ListHouseworkTemplates:output_type -> shw.ListHouseworkTemplatesResponse
	41, // 62: shw.HouseworkTemplateService.CreateHouseworkTemplate:output_type -> shw.CommonResponse
	41, // 63: shw.HouseworkTemplateService.UpdateHouseworkTemplate:output_type -> shw.CommonResponse
	41, // 64: shw.HouseworkTemplateService.DeleteHouseworkTemplate:output_type -> shw.CommonResponse
	26, // 65: shw.HouseworkScheduleService.GetHouseworkSchedule:output_type -> shw.GetHouseworkScheduleResponse
	28, // 66: shw.HouseworkScheduleService.ListHouseworkSchedules:output_type -> shw.ListHouseworkSchedulesResponse
	41, // 67: shw.HouseworkScheduleService.CreateHouseworkSchedule:output_type -> shw.CommonResponse
	41, // 68: shw.HouseworkScheduleService.UpdateHouseworkSchedule:output_type -> shw.CommonResponse
	41, // 69: shw.HouseworkScheduleService.DeleteHouseworkSchedule:output_type -> shw.CommonResponse
	48, // [48:70] is the sub-list for method output_type
	26, // [26:48] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_housework_proto_init() }
func file_housework_proto_init() {
	if File_housework_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_housework_proto_rawDesc), len(file_housework_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_housework_proto_goTypes,
		DependencyIndexes: file_housework_proto_depIdxs,
		EnumInfos:         file_housework_proto_enumTypes,
		MessageInfos:      file_housework_proto_msgTypes,
	}.Build()
	File_housework_proto = out.File
	file_housework_proto_goTypes = nil
	file_housework_proto_depIdxs = nil
}
