// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: point.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Point         int64                  `protobuf:"varint,2,opt,name=point,proto3" json:"point,omitempty"`
	User          *UserInfo              `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPoint) Reset() {
	*x = UserPoint{}
	mi := &file_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPoint) ProtoMessage() {}

func (x *UserPoint) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPoint.ProtoReflect.Descriptor instead.
func (*UserPoint) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{0}
}

func (x *UserPoint) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserPoint) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *UserPoint) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // was userId
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPointRequest) Reset() {
	*x = GetUserPointRequest{}
	mi := &file_point_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointRequest) ProtoMessage() {}

func (x *GetUserPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointRequest.ProtoReflect.Descriptor instead.
func (*GetUserPointRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserPointRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *UserPoint             `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPointResponse) Reset() {
	*x = GetUserPointResponse{}
	mi := &file_point_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPointResponse) ProtoMessage() {}

func (x *GetUserPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPointResponse.ProtoReflect.Descriptor instead.
func (*GetUserPointResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPointResponse) GetPoint() *UserPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type CreateUserPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *UserPoint             `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserPointRequest) Reset() {
	*x = CreateUserPointRequest{}
	mi := &file_point_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPointRequest) ProtoMessage() {}

func (x *CreateUserPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPointRequest.ProtoReflect.Descriptor instead.
func (*CreateUserPointRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserPointRequest) GetPoint() *UserPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type UpdateUserPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *UserPoint             `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPointRequest) Reset() {
	*x = UpdateUserPointRequest{}
	mi := &file_point_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPointRequest) ProtoMessage() {}

func (x *UpdateUserPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPointRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserPointRequest) GetPoint() *UserPoint {
	if x != nil {
		return x.Point
	}
	return nil
}

type DeleteUserPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserPointRequest) Reset() {
	*x = DeleteUserPointRequest{}
	mi := &file_point_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPointRequest) ProtoMessage() {}

func (x *DeleteUserPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPointRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserPointRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListFamilyPointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyPointsRequest) Reset() {
	*x = ListFamilyPointsRequest{}
	mi := &file_point_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyPointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyPointsRequest) ProtoMessage() {}

func (x *ListFamilyPointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyPointsRequest.ProtoReflect.Descriptor instead.
func (*ListFamilyPointsRequest) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{6}
}

func (x *ListFamilyPointsRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListFamilyPointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*UserPoint           `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyPointsResponse) Reset() {
	*x = ListFamilyPointsResponse{}
	mi := &file_point_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyPointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyPointsResponse) ProtoMessage() {}

func (x *ListFamilyPointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_point_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyPointsResponse.ProtoReflect.Descriptor instead.
func (*ListFamilyPointsResponse) Descriptor() ([]byte, []int) {
	return file_point_proto_rawDescGZIP(), []int{7}
}

func (x *ListFamilyPointsResponse) GetPoints() []*UserPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_point_proto protoreflect.FileDescriptor

const file_point_proto_rawDesc = "" +
	"\n" +
	"\vpoint.proto\x12\x03shw\x1a\fcommon.proto\"T\n" +
	"\tUserPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05point\x18\x02 \x01(\x03R\x05point\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.shw.UserInfoR\x04user\".\n" +
	"\x13GetUserPointRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"<\n" +
	"\x14GetUserPointResponse\x12$\n" +
	"\x05point\x18\x01 \x01(\v2\x0e.shw.UserPointR\x05point\">\n" +
	"\x16CreateUserPointRequest\x12$\n" +
	"\x05point\x18\x01 \x01(\v2\x0e.shw.UserPointR\x05point\">\n" +
	"\x16UpdateUserPointRequest\x12$\n" +
	"\x05point\x18\x01 \x01(\v2\x0e.shw.UserPointR\x05point\"(\n" +
	"\x16DeleteUserPointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"6\n" +
	"\x17ListFamilyPointsRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"B\n" +
	"\x18ListFamilyPointsResponse\x12&\n" +
	"\x06points\x18\x01 \x03(\v2\x0e.shw.UserPointR\x06points2\xae\x02\n" +
	"\x10UserPointService\x12E\n" +
	"\fGetUserPoint\x12\x18.shw.GetUserPointRequest\x1a\x19.shw.GetUserPointResponse\"\x00\x12E\n" +
	"\x0fCreateUserPoint\x12\x1b.shw.CreateUserPointRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fUpdateUserPoint\x12\x1b.shw.UpdateUserPointRequest\x1a\x13.shw.CommonResponse\"\x00\x12E\n" +
	"\x0fDeleteUserPoint\x12\x1b.shw.DeleteUserPointRequest\x1a\x13.shw.CommonResponse\"\x002g\n" +
	"\x12FamilyPointService\x12Q\n" +
	"\x10ListFamilyPoints\x12\x1c.shw.ListFamilyPointsRequest\x1a\x1d.shw.ListFamilyPointsResponse\"\x00B\x12Z\x10shwgrpc/pkg/grpcb\x06proto3"

var (
	file_point_proto_rawDescOnce sync.Once
	file_point_proto_rawDescData []byte
)

func file_point_proto_rawDescGZIP() []byte {
	file_point_proto_rawDescOnce.Do(func() {
		file_point_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)))
	})
	return file_point_proto_rawDescData
}

var file_point_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_point_proto_goTypes = []any{
	(*UserPoint)(nil),                // 0: shw.UserPoint
	(*GetUserPointRequest)(nil),      // 1: shw.GetUserPointRequest
	(*GetUserPointResponse)(nil),     // 2: shw.GetUserPointResponse
	(*CreateUserPointRequest)(nil),   // 3: shw.CreateUserPointRequest
	(*UpdateUserPointRequest)(nil),   // 4: shw.UpdateUserPointRequest
	(*DeleteUserPointRequest)(nil),   // 5: shw.DeleteUserPointRequest
	(*ListFamilyPointsRequest)(nil),  // 6: shw.ListFamilyPointsRequest
	(*ListFamilyPointsResponse)(nil), // 7: shw.ListFamilyPointsResponse
	(*UserInfo)(nil),                 // 8: shw.UserInfo
	(*CommonResponse)(nil),           // 9: shw.CommonResponse
}
var file_point_proto_depIdxs = []int32{
	8,  // 0: shw.UserPoint.user:type_name -> shw.UserInfo
	0,  // 1: shw.GetUserPointResponse.point:type_name -> shw.UserPoint
	0,  // 2: shw.CreateUserPointRequest.point:type_name -> shw.UserPoint
	0,  // 3: shw.UpdateUserPointRequest.point:type_name -> shw.UserPoint
	0,  // 4: shw.ListFamilyPointsResponse.points:type_name -> shw.UserPoint
	1,  // 5: shw.UserPointService.GetUserPoint:input_type -> shw.GetUserPointRequest
	3,  // 6: shw.UserPointService.CreateUserPoint:input_type -> shw.CreateUserPointRequest
	4,  // 7: shw.UserPointService.UpdateUserPoint:input_type -> shw.UpdateUserPointRequest
	5,  // 8: shw.UserPointService.DeleteUserPoint:input_type -> shw.DeleteUserPointRequest
	6,  // 9: shw.FamilyPointService.ListFamilyPoints:input_type -> shw.ListFamilyPointsRequest
	2,  // 10: shw.UserPointService.GetUserPoint:output_type -> shw.GetUserPointResponse
	9,  // 11: shw.UserPointService.CreateUserPoint:output_type -> shw.CommonResponse
	9,  // 12: shw.UserPointService.UpdateUserPoint:output_type -> shw.CommonResponse
	9,  // 13: shw.UserPointService.DeleteUserPoint:output_type -> shw.CommonResponse
	7,  // 14: shw.FamilyPointService.ListFamilyPoints:output_type -> shw.ListFamilyPointsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_point_proto_init() }
func file_point_proto_init() {
	if File_point_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_point_proto_rawDesc), len(file_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_point_proto_goTypes,
		DependencyIndexes: file_point_proto_depIdxs,
		MessageInfos:      file_point_proto_msgTypes,
	}.Build()
	File_point_proto = out.File
	file_point_proto_goTypes = nil
	file_point_proto_depIdxs = nil
}
