// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoleId        uint64                 `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	FamilyId      uint64                 `protobuf:"varint,4,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyUser) Reset() {
	*x = FamilyUser{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyUser) ProtoMessage() {}

func (x *FamilyUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyUser.ProtoReflect.Descriptor instead.
func (*FamilyUser) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyUser) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FamilyUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FamilyUser) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *FamilyUser) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListFamilyUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      uint64                 `protobuf:"varint,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"` // was GetBelongToUserRequest.family_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyUsersRequest) Reset() {
	*x = ListFamilyUsersRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyUsersRequest) ProtoMessage() {}

func (x *ListFamilyUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyUsersRequest.ProtoReflect.Descriptor instead.
func (*ListFamilyUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *ListFamilyUsersRequest) GetFamilyId() uint64 {
	if x != nil {
		return x.FamilyId
	}
	return 0
}

type ListFamilyUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*FamilyUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFamilyUsersResponse) Reset() {
	*x = ListFamilyUsersResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFamilyUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFamilyUsersResponse) ProtoMessage() {}

func (x *ListFamilyUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFamilyUsersResponse.ProtoReflect.Descriptor instead.
func (*ListFamilyUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *ListFamilyUsersResponse) GetUsers() []*FamilyUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        uint64                 `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleRequest) Reset() {
	*x = UpdateUserRoleRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleRequest) ProtoMessage() {}

func (x *UpdateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRoleRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRoleRequest) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x03shw\x1a\fcommon.proto\"f\n" +
	"\n" +
	"FamilyUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x04R\x06roleId\x12\x1b\n" +
	"\tfamily_id\x18\x04 \x01(\x04R\bfamilyId\"5\n" +
	"\x16ListFamilyUsersRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\x04R\bfamilyId\"@\n" +
	"\x17ListFamilyUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.shw.FamilyUserR\x05users\"I\n" +
	"\x15UpdateUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x04R\x06roleId2\xa2\x01\n" +
	"\vUserService\x12N\n" +
	"\x0fListFamilyUsers\x12\x1b.shw.ListFamilyUsersRequest\x1a\x1c.shw.ListFamilyUsersResponse\"\x00\x12C\n" +
	"\x0eUpdateUserRole\x12\x1a.shw.UpdateUserRoleRequest\x1a\x13.shw.CommonResponse\"\x00B\x12Z\x10shwgrpc/pkg/grpcb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*FamilyUser)(nil),              // 0: shw.FamilyUser
	(*ListFamilyUsersRequest)(nil),  // 1: shw.ListFamilyUsersRequest
	(*ListFamilyUsersResponse)(nil), // 2: shw.ListFamilyUsersResponse
	(*UpdateUserRoleRequest)(nil),   // 3: shw.UpdateUserRoleRequest
	(*CommonResponse)(nil),          // 4: shw.CommonResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: shw.ListFamilyUsersResponse.users:type_name -> shw.FamilyUser
	1, // 1: shw.UserService.ListFamilyUsers:input_type -> shw.ListFamilyUsersRequest
	3, // 2: shw.UserService.UpdateUserRole:input_type -> shw.UpdateUserRoleRequest
	2, // 3: shw.UserService.ListFamilyUsers:output_type -> shw.ListFamilyUsersResponse
	4, // 4: shw.UserService.UpdateUserRole:output_type -> shw.CommonResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
