// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: family.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	grpc "shwgrpc/pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FamilyServiceName is the fully-qualified name of the FamilyService service.
	FamilyServiceName = "shw.FamilyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FamilyServiceGetFamilyProcedure is the fully-qualified name of the FamilyService's GetFamily RPC.
	FamilyServiceGetFamilyProcedure = "/shw.FamilyService/GetFamily"
	// FamilyServiceCreateFamilyProcedure is the fully-qualified name of the FamilyService's
	// CreateFamily RPC.
	FamilyServiceCreateFamilyProcedure = "/shw.FamilyService/CreateFamily"
	// FamilyServiceUpdateFamilyProcedure is the fully-qualified name of the FamilyService's
	// UpdateFamily RPC.
	FamilyServiceUpdateFamilyProcedure = "/shw.FamilyService/UpdateFamily"
	// FamilyServiceDeleteFamilyProcedure is the fully-qualified name of the FamilyService's
	// DeleteFamily RPC.
	FamilyServiceDeleteFamilyProcedure = "/shw.FamilyService/DeleteFamily"
	// FamilyServiceAddFamilyMemberProcedure is the fully-qualified name of the FamilyService's
	// AddFamilyMember RPC.
	FamilyServiceAddFamilyMemberProcedure = "/shw.FamilyService/AddFamilyMember"
	// FamilyServiceGetFamilyRoleProcedure is the fully-qualified name of the FamilyService's
	// GetFamilyRole RPC.
	FamilyServiceGetFamilyRoleProcedure = "/shw.FamilyService/GetFamilyRole"
	// FamilyServiceCreateFamilyRoleProcedure is the fully-qualified name of the FamilyService's
	// CreateFamilyRole RPC.
	FamilyServiceCreateFamilyRoleProcedure = "/shw.FamilyService/CreateFamilyRole"
	// FamilyServiceUpdateFamilyRoleProcedure is the fully-qualified name of the FamilyService's
	// UpdateFamilyRole RPC.
	FamilyServiceUpdateFamilyRoleProcedure = "/shw.FamilyService/UpdateFamilyRole"
	// FamilyServiceDeleteFamilyRoleProcedure is the fully-qualified name of the FamilyService's
	// DeleteFamilyRole RPC.
	FamilyServiceDeleteFamilyRoleProcedure = "/shw.FamilyService/DeleteFamilyRole"
)

// FamilyServiceClient is a client for the shw.FamilyService service.
type FamilyServiceClient interface {
	GetFamily(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyResponse], error)
	CreateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	UpdateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	DeleteFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	AddFamilyMember(context.Context, *connect.Request[grpc.AddFamilyMemberRequest]) (*connect.Response[grpc.CommonResponse], error)
	GetFamilyRole(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyRoleResponse], error)
	CreateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error)
	UpdateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error)
	DeleteFamilyRole(context.Context, *connect.Request[grpc.FamilyRoleRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewFamilyServiceClient constructs a client for the shw.FamilyService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFamilyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FamilyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	familyServiceMethods := grpc.File_family_proto.Services().ByName("FamilyService").Methods()
	return &familyServiceClient{
		getFamily: connect.NewClient[grpc.FamilyRequest, grpc.FamilyResponse](
			httpClient,
			baseURL+FamilyServiceGetFamilyProcedure,
			connect.WithSchema(familyServiceMethods.ByName("GetFamily")),
			connect.WithClientOptions(opts...),
		),
		createFamily: connect.NewClient[grpc.Family, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceCreateFamilyProcedure,
			connect.WithSchema(familyServiceMethods.ByName("CreateFamily")),
			connect.WithClientOptions(opts...),
		),
		updateFamily: connect.NewClient[grpc.Family, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceUpdateFamilyProcedure,
			connect.WithSchema(familyServiceMethods.ByName("UpdateFamily")),
			connect.WithClientOptions(opts...),
		),
		deleteFamily: connect.NewClient[grpc.Family, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceDeleteFamilyProcedure,
			connect.WithSchema(familyServiceMethods.ByName("DeleteFamily")),
			connect.WithClientOptions(opts...),
		),
		addFamilyMember: connect.NewClient[grpc.AddFamilyMemberRequest, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceAddFamilyMemberProcedure,
			connect.WithSchema(familyServiceMethods.ByName("AddFamilyMember")),
			connect.WithClientOptions(opts...),
		),
		getFamilyRole: connect.NewClient[grpc.FamilyRequest, grpc.FamilyRoleResponse](
			httpClient,
			baseURL+FamilyServiceGetFamilyRoleProcedure,
			connect.WithSchema(familyServiceMethods.ByName("GetFamilyRole")),
			connect.WithClientOptions(opts...),
		),
		createFamilyRole: connect.NewClient[grpc.FamilyRole, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceCreateFamilyRoleProcedure,
			connect.WithSchema(familyServiceMethods.ByName("CreateFamilyRole")),
			connect.WithClientOptions(opts...),
		),
		updateFamilyRole: connect.NewClient[grpc.FamilyRole, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceUpdateFamilyRoleProcedure,
			connect.WithSchema(familyServiceMethods.ByName("UpdateFamilyRole")),
			connect.WithClientOptions(opts...),
		),
		deleteFamilyRole: connect.NewClient[grpc.FamilyRoleRequest, grpc.CommonResponse](
			httpClient,
			baseURL+FamilyServiceDeleteFamilyRoleProcedure,
			connect.WithSchema(familyServiceMethods.ByName("DeleteFamilyRole")),
			connect.WithClientOptions(opts...),
		),
	}
}

// familyServiceClient implements FamilyServiceClient.
type familyServiceClient struct {
	getFamily        *connect.Client[grpc.FamilyRequest, grpc.FamilyResponse]
	createFamily     *connect.Client[grpc.Family, grpc.CommonResponse]
	updateFamily     *connect.Client[grpc.Family, grpc.CommonResponse]
	deleteFamily     *connect.Client[grpc.Family, grpc.CommonResponse]
	addFamilyMember  *connect.Client[grpc.AddFamilyMemberRequest, grpc.CommonResponse]
	getFamilyRole    *connect.Client[grpc.FamilyRequest, grpc.FamilyRoleResponse]
	createFamilyRole *connect.Client[grpc.FamilyRole, grpc.CommonResponse]
	updateFamilyRole *connect.Client[grpc.FamilyRole, grpc.CommonResponse]
	deleteFamilyRole *connect.Client[grpc.FamilyRoleRequest, grpc.CommonResponse]
}

// GetFamily calls shw.FamilyService.GetFamily.
func (c *familyServiceClient) GetFamily(ctx context.Context, req *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyResponse], error) {
	return c.getFamily.CallUnary(ctx, req)
}

// CreateFamily calls shw.FamilyService.CreateFamily.
func (c *familyServiceClient) CreateFamily(ctx context.Context, req *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createFamily.CallUnary(ctx, req)
}

// UpdateFamily calls shw.FamilyService.UpdateFamily.
func (c *familyServiceClient) UpdateFamily(ctx context.Context, req *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateFamily.CallUnary(ctx, req)
}

// DeleteFamily calls shw.FamilyService.DeleteFamily.
func (c *familyServiceClient) DeleteFamily(ctx context.Context, req *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deleteFamily.CallUnary(ctx, req)
}

// AddFamilyMember calls shw.FamilyService.AddFamilyMember.
func (c *familyServiceClient) AddFamilyMember(ctx context.Context, req *connect.Request[grpc.AddFamilyMemberRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.addFamilyMember.CallUnary(ctx, req)
}

// GetFamilyRole calls shw.FamilyService.GetFamilyRole.
func (c *familyServiceClient) GetFamilyRole(ctx context.Context, req *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyRoleResponse], error) {
	return c.getFamilyRole.CallUnary(ctx, req)
}

// CreateFamilyRole calls shw.FamilyService.CreateFamilyRole.
func (c *familyServiceClient) CreateFamilyRole(ctx context.Context, req *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createFamilyRole.CallUnary(ctx, req)
}

// UpdateFamilyRole calls shw.FamilyService.UpdateFamilyRole.
func (c *familyServiceClient) UpdateFamilyRole(ctx context.Context, req *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateFamilyRole.CallUnary(ctx, req)
}

// DeleteFamilyRole calls shw.FamilyService.DeleteFamilyRole.
func (c *familyServiceClient) DeleteFamilyRole(ctx context.Context, req *connect.Request[grpc.FamilyRoleRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deleteFamilyRole.CallUnary(ctx, req)
}

// FamilyServiceHandler is an implementation of the shw.FamilyService service.
type FamilyServiceHandler interface {
	GetFamily(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyResponse], error)
	CreateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	UpdateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	DeleteFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error)
	AddFamilyMember(context.Context, *connect.Request[grpc.AddFamilyMemberRequest]) (*connect.Response[grpc.CommonResponse], error)
	GetFamilyRole(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyRoleResponse], error)
	CreateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error)
	UpdateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error)
	DeleteFamilyRole(context.Context, *connect.Request[grpc.FamilyRoleRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewFamilyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFamilyServiceHandler(svc FamilyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	familyServiceMethods := grpc.File_family_proto.Services().ByName("FamilyService").Methods()
	familyServiceGetFamilyHandler := connect.NewUnaryHandler(
		FamilyServiceGetFamilyProcedure,
		svc.GetFamily,
		connect.WithSchema(familyServiceMethods.ByName("GetFamily")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceCreateFamilyHandler := connect.NewUnaryHandler(
		FamilyServiceCreateFamilyProcedure,
		svc.CreateFamily,
		connect.WithSchema(familyServiceMethods.ByName("CreateFamily")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceUpdateFamilyHandler := connect.NewUnaryHandler(
		FamilyServiceUpdateFamilyProcedure,
		svc.UpdateFamily,
		connect.WithSchema(familyServiceMethods.ByName("UpdateFamily")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceDeleteFamilyHandler := connect.NewUnaryHandler(
		FamilyServiceDeleteFamilyProcedure,
		svc.DeleteFamily,
		connect.WithSchema(familyServiceMethods.ByName("DeleteFamily")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceAddFamilyMemberHandler := connect.NewUnaryHandler(
		FamilyServiceAddFamilyMemberProcedure,
		svc.AddFamilyMember,
		connect.WithSchema(familyServiceMethods.ByName("AddFamilyMember")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceGetFamilyRoleHandler := connect.NewUnaryHandler(
		FamilyServiceGetFamilyRoleProcedure,
		svc.GetFamilyRole,
		connect.WithSchema(familyServiceMethods.ByName("GetFamilyRole")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceCreateFamilyRoleHandler := connect.NewUnaryHandler(
		FamilyServiceCreateFamilyRoleProcedure,
		svc.CreateFamilyRole,
		connect.WithSchema(familyServiceMethods.ByName("CreateFamilyRole")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceUpdateFamilyRoleHandler := connect.NewUnaryHandler(
		FamilyServiceUpdateFamilyRoleProcedure,
		svc.UpdateFamilyRole,
		connect.WithSchema(familyServiceMethods.ByName("UpdateFamilyRole")),
		connect.WithHandlerOptions(opts...),
	)
	familyServiceDeleteFamilyRoleHandler := connect.NewUnaryHandler(
		FamilyServiceDeleteFamilyRoleProcedure,
		svc.DeleteFamilyRole,
		connect.WithSchema(familyServiceMethods.ByName("DeleteFamilyRole")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.FamilyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FamilyServiceGetFamilyProcedure:
			familyServiceGetFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceCreateFamilyProcedure:
			familyServiceCreateFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceUpdateFamilyProcedure:
			familyServiceUpdateFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceDeleteFamilyProcedure:
			familyServiceDeleteFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceAddFamilyMemberProcedure:
			familyServiceAddFamilyMemberHandler.ServeHTTP(w, r)
		case FamilyServiceGetFamilyRoleProcedure:
			familyServiceGetFamilyRoleHandler.ServeHTTP(w, r)
		case FamilyServiceCreateFamilyRoleProcedure:
			familyServiceCreateFamilyRoleHandler.ServeHTTP(w, r)
		case FamilyServiceUpdateFamilyRoleProcedure:
			familyServiceUpdateFamilyRoleHandler.ServeHTTP(w, r)
		case FamilyServiceDeleteFamilyRoleProcedure:
			familyServiceDeleteFamilyRoleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFamilyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFamilyServiceHandler struct{}

func (UnimplementedFamilyServiceHandler) GetFamily(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.GetFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) CreateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.CreateFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) UpdateFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.UpdateFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) DeleteFamily(context.Context, *connect.Request[grpc.Family]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.DeleteFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) AddFamilyMember(context.Context, *connect.Request[grpc.AddFamilyMemberRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.AddFamilyMember is not implemented"))
}

func (UnimplementedFamilyServiceHandler) GetFamilyRole(context.Context, *connect.Request[grpc.FamilyRequest]) (*connect.Response[grpc.FamilyRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.GetFamilyRole is not implemented"))
}

func (UnimplementedFamilyServiceHandler) CreateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.CreateFamilyRole is not implemented"))
}

func (UnimplementedFamilyServiceHandler) UpdateFamilyRole(context.Context, *connect.Request[grpc.FamilyRole]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.UpdateFamilyRole is not implemented"))
}

func (UnimplementedFamilyServiceHandler) DeleteFamilyRole(context.Context, *connect.Request[grpc.FamilyRoleRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyService.DeleteFamilyRole is not implemented"))
}
