// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: housework.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	grpc "pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HouseworkServiceName is the fully-qualified name of the HouseworkService service.
	HouseworkServiceName = "shw.HouseworkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HouseworkServiceGetHouseworkProcedure is the fully-qualified name of the HouseworkService's
	// GetHousework RPC.
	HouseworkServiceGetHouseworkProcedure = "/shw.HouseworkService/GetHousework"
	// HouseworkServiceGetHouseworkDetailProcedure is the fully-qualified name of the HouseworkService's
	// GetHouseworkDetail RPC.
	HouseworkServiceGetHouseworkDetailProcedure = "/shw.HouseworkService/GetHouseworkDetail"
	// HouseworkServiceCreateHouseworkProcedure is the fully-qualified name of the HouseworkService's
	// CreateHousework RPC.
	HouseworkServiceCreateHouseworkProcedure = "/shw.HouseworkService/CreateHousework"
	// HouseworkServiceUpdateHouseworkProcedure is the fully-qualified name of the HouseworkService's
	// UpdateHousework RPC.
	HouseworkServiceUpdateHouseworkProcedure = "/shw.HouseworkService/UpdateHousework"
	// HouseworkServiceFinishHouseworkProcedure is the fully-qualified name of the HouseworkService's
	// FinishHousework RPC.
	HouseworkServiceFinishHouseworkProcedure = "/shw.HouseworkService/FinishHousework"
	// HouseworkServiceDeleteHouseworkProcedure is the fully-qualified name of the HouseworkService's
	// DeleteHousework RPC.
	HouseworkServiceDeleteHouseworkProcedure = "/shw.HouseworkService/DeleteHousework"
	// HouseworkServiceGetHouseworkMemoProcedure is the fully-qualified name of the HouseworkService's
	// GetHouseworkMemo RPC.
	HouseworkServiceGetHouseworkMemoProcedure = "/shw.HouseworkService/GetHouseworkMemo"
	// HouseworkServiceCreateHouseworkMemoProcedure is the fully-qualified name of the
	// HouseworkService's CreateHouseworkMemo RPC.
	HouseworkServiceCreateHouseworkMemoProcedure = "/shw.HouseworkService/CreateHouseworkMemo"
	// HouseworkServiceUpdateHouseworkMemoProcedure is the fully-qualified name of the
	// HouseworkService's UpdateHouseworkMemo RPC.
	HouseworkServiceUpdateHouseworkMemoProcedure = "/shw.HouseworkService/UpdateHouseworkMemo"
	// HouseworkServiceDeleteHouseworkMemoProcedure is the fully-qualified name of the
	// HouseworkService's DeleteHouseworkMemo RPC.
	HouseworkServiceDeleteHouseworkMemoProcedure = "/shw.HouseworkService/DeleteHouseworkMemo"
	// HouseworkServiceGetHouseworkPointProcedure is the fully-qualified name of the HouseworkService's
	// GetHouseworkPoint RPC.
	HouseworkServiceGetHouseworkPointProcedure = "/shw.HouseworkService/GetHouseworkPoint"
	// HouseworkServiceGetHouseworkPointHistoryProcedure is the fully-qualified name of the
	// HouseworkService's GetHouseworkPointHistory RPC.
	HouseworkServiceGetHouseworkPointHistoryProcedure = "/shw.HouseworkService/GetHouseworkPointHistory"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	houseworkServiceServiceDescriptor                        = grpc.File_housework_proto.Services().ByName("HouseworkService")
	houseworkServiceGetHouseworkMethodDescriptor             = houseworkServiceServiceDescriptor.Methods().ByName("GetHousework")
	houseworkServiceGetHouseworkDetailMethodDescriptor       = houseworkServiceServiceDescriptor.Methods().ByName("GetHouseworkDetail")
	houseworkServiceCreateHouseworkMethodDescriptor          = houseworkServiceServiceDescriptor.Methods().ByName("CreateHousework")
	houseworkServiceUpdateHouseworkMethodDescriptor          = houseworkServiceServiceDescriptor.Methods().ByName("UpdateHousework")
	houseworkServiceFinishHouseworkMethodDescriptor          = houseworkServiceServiceDescriptor.Methods().ByName("FinishHousework")
	houseworkServiceDeleteHouseworkMethodDescriptor          = houseworkServiceServiceDescriptor.Methods().ByName("DeleteHousework")
	houseworkServiceGetHouseworkMemoMethodDescriptor         = houseworkServiceServiceDescriptor.Methods().ByName("GetHouseworkMemo")
	houseworkServiceCreateHouseworkMemoMethodDescriptor      = houseworkServiceServiceDescriptor.Methods().ByName("CreateHouseworkMemo")
	houseworkServiceUpdateHouseworkMemoMethodDescriptor      = houseworkServiceServiceDescriptor.Methods().ByName("UpdateHouseworkMemo")
	houseworkServiceDeleteHouseworkMemoMethodDescriptor      = houseworkServiceServiceDescriptor.Methods().ByName("DeleteHouseworkMemo")
	houseworkServiceGetHouseworkPointMethodDescriptor        = houseworkServiceServiceDescriptor.Methods().ByName("GetHouseworkPoint")
	houseworkServiceGetHouseworkPointHistoryMethodDescriptor = houseworkServiceServiceDescriptor.Methods().ByName("GetHouseworkPointHistory")
)

// HouseworkServiceClient is a client for the shw.HouseworkService service.
type HouseworkServiceClient interface {
	GetHousework(context.Context, *connect.Request[grpc.HouseworkRequest]) (*connect.Response[grpc.HouseworkResponse], error)
	GetHouseworkDetail(context.Context, *connect.Request[grpc.HouseworkDetailRequest]) (*connect.Response[grpc.HouseworkDetailResponse], error)
	CreateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	UpdateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	FinishHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	DeleteHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	GetHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemoRequest]) (*connect.Response[grpc.HouseworkMemoResponse], error)
	CreateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	UpdateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	DeleteHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	GetHouseworkPoint(context.Context, *connect.Request[grpc.HouseworkPointRequest]) (*connect.Response[grpc.HouseworkPointResponse], error)
	GetHouseworkPointHistory(context.Context, *connect.Request[grpc.HouseworkPointHistoryRequest]) (*connect.Response[grpc.HouseworkPointHistoryResponse], error)
}

// NewHouseworkServiceClient constructs a client for the shw.HouseworkService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHouseworkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HouseworkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &houseworkServiceClient{
		getHousework: connect.NewClient[grpc.HouseworkRequest, grpc.HouseworkResponse](
			httpClient,
			baseURL+HouseworkServiceGetHouseworkProcedure,
			connect.WithSchema(houseworkServiceGetHouseworkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getHouseworkDetail: connect.NewClient[grpc.HouseworkDetailRequest, grpc.HouseworkDetailResponse](
			httpClient,
			baseURL+HouseworkServiceGetHouseworkDetailProcedure,
			connect.WithSchema(houseworkServiceGetHouseworkDetailMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createHousework: connect.NewClient[grpc.Housework, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceCreateHouseworkProcedure,
			connect.WithSchema(houseworkServiceCreateHouseworkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateHousework: connect.NewClient[grpc.Housework, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceUpdateHouseworkProcedure,
			connect.WithSchema(houseworkServiceUpdateHouseworkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		finishHousework: connect.NewClient[grpc.Housework, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceFinishHouseworkProcedure,
			connect.WithSchema(houseworkServiceFinishHouseworkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteHousework: connect.NewClient[grpc.Housework, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceDeleteHouseworkProcedure,
			connect.WithSchema(houseworkServiceDeleteHouseworkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getHouseworkMemo: connect.NewClient[grpc.HouseworkMemoRequest, grpc.HouseworkMemoResponse](
			httpClient,
			baseURL+HouseworkServiceGetHouseworkMemoProcedure,
			connect.WithSchema(houseworkServiceGetHouseworkMemoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createHouseworkMemo: connect.NewClient[grpc.HouseworkMemo, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceCreateHouseworkMemoProcedure,
			connect.WithSchema(houseworkServiceCreateHouseworkMemoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateHouseworkMemo: connect.NewClient[grpc.HouseworkMemo, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceUpdateHouseworkMemoProcedure,
			connect.WithSchema(houseworkServiceUpdateHouseworkMemoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deleteHouseworkMemo: connect.NewClient[grpc.HouseworkMemo, grpc.CommonResponse](
			httpClient,
			baseURL+HouseworkServiceDeleteHouseworkMemoProcedure,
			connect.WithSchema(houseworkServiceDeleteHouseworkMemoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getHouseworkPoint: connect.NewClient[grpc.HouseworkPointRequest, grpc.HouseworkPointResponse](
			httpClient,
			baseURL+HouseworkServiceGetHouseworkPointProcedure,
			connect.WithSchema(houseworkServiceGetHouseworkPointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getHouseworkPointHistory: connect.NewClient[grpc.HouseworkPointHistoryRequest, grpc.HouseworkPointHistoryResponse](
			httpClient,
			baseURL+HouseworkServiceGetHouseworkPointHistoryProcedure,
			connect.WithSchema(houseworkServiceGetHouseworkPointHistoryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// houseworkServiceClient implements HouseworkServiceClient.
type houseworkServiceClient struct {
	getHousework             *connect.Client[grpc.HouseworkRequest, grpc.HouseworkResponse]
	getHouseworkDetail       *connect.Client[grpc.HouseworkDetailRequest, grpc.HouseworkDetailResponse]
	createHousework          *connect.Client[grpc.Housework, grpc.CommonResponse]
	updateHousework          *connect.Client[grpc.Housework, grpc.CommonResponse]
	finishHousework          *connect.Client[grpc.Housework, grpc.CommonResponse]
	deleteHousework          *connect.Client[grpc.Housework, grpc.CommonResponse]
	getHouseworkMemo         *connect.Client[grpc.HouseworkMemoRequest, grpc.HouseworkMemoResponse]
	createHouseworkMemo      *connect.Client[grpc.HouseworkMemo, grpc.CommonResponse]
	updateHouseworkMemo      *connect.Client[grpc.HouseworkMemo, grpc.CommonResponse]
	deleteHouseworkMemo      *connect.Client[grpc.HouseworkMemo, grpc.CommonResponse]
	getHouseworkPoint        *connect.Client[grpc.HouseworkPointRequest, grpc.HouseworkPointResponse]
	getHouseworkPointHistory *connect.Client[grpc.HouseworkPointHistoryRequest, grpc.HouseworkPointHistoryResponse]
}

// GetHousework calls shw.HouseworkService.GetHousework.
func (c *houseworkServiceClient) GetHousework(ctx context.Context, req *connect.Request[grpc.HouseworkRequest]) (*connect.Response[grpc.HouseworkResponse], error) {
	return c.getHousework.CallUnary(ctx, req)
}

// GetHouseworkDetail calls shw.HouseworkService.GetHouseworkDetail.
func (c *houseworkServiceClient) GetHouseworkDetail(ctx context.Context, req *connect.Request[grpc.HouseworkDetailRequest]) (*connect.Response[grpc.HouseworkDetailResponse], error) {
	return c.getHouseworkDetail.CallUnary(ctx, req)
}

// CreateHousework calls shw.HouseworkService.CreateHousework.
func (c *houseworkServiceClient) CreateHousework(ctx context.Context, req *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createHousework.CallUnary(ctx, req)
}

// UpdateHousework calls shw.HouseworkService.UpdateHousework.
func (c *houseworkServiceClient) UpdateHousework(ctx context.Context, req *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateHousework.CallUnary(ctx, req)
}

// FinishHousework calls shw.HouseworkService.FinishHousework.
func (c *houseworkServiceClient) FinishHousework(ctx context.Context, req *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return c.finishHousework.CallUnary(ctx, req)
}

// DeleteHousework calls shw.HouseworkService.DeleteHousework.
func (c *houseworkServiceClient) DeleteHousework(ctx context.Context, req *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deleteHousework.CallUnary(ctx, req)
}

// GetHouseworkMemo calls shw.HouseworkService.GetHouseworkMemo.
func (c *houseworkServiceClient) GetHouseworkMemo(ctx context.Context, req *connect.Request[grpc.HouseworkMemoRequest]) (*connect.Response[grpc.HouseworkMemoResponse], error) {
	return c.getHouseworkMemo.CallUnary(ctx, req)
}

// CreateHouseworkMemo calls shw.HouseworkService.CreateHouseworkMemo.
func (c *houseworkServiceClient) CreateHouseworkMemo(ctx context.Context, req *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createHouseworkMemo.CallUnary(ctx, req)
}

// UpdateHouseworkMemo calls shw.HouseworkService.UpdateHouseworkMemo.
func (c *houseworkServiceClient) UpdateHouseworkMemo(ctx context.Context, req *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateHouseworkMemo.CallUnary(ctx, req)
}

// DeleteHouseworkMemo calls shw.HouseworkService.DeleteHouseworkMemo.
func (c *houseworkServiceClient) DeleteHouseworkMemo(ctx context.Context, req *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deleteHouseworkMemo.CallUnary(ctx, req)
}

// GetHouseworkPoint calls shw.HouseworkService.GetHouseworkPoint.
func (c *houseworkServiceClient) GetHouseworkPoint(ctx context.Context, req *connect.Request[grpc.HouseworkPointRequest]) (*connect.Response[grpc.HouseworkPointResponse], error) {
	return c.getHouseworkPoint.CallUnary(ctx, req)
}

// GetHouseworkPointHistory calls shw.HouseworkService.GetHouseworkPointHistory.
func (c *houseworkServiceClient) GetHouseworkPointHistory(ctx context.Context, req *connect.Request[grpc.HouseworkPointHistoryRequest]) (*connect.Response[grpc.HouseworkPointHistoryResponse], error) {
	return c.getHouseworkPointHistory.CallUnary(ctx, req)
}

// HouseworkServiceHandler is an implementation of the shw.HouseworkService service.
type HouseworkServiceHandler interface {
	GetHousework(context.Context, *connect.Request[grpc.HouseworkRequest]) (*connect.Response[grpc.HouseworkResponse], error)
	GetHouseworkDetail(context.Context, *connect.Request[grpc.HouseworkDetailRequest]) (*connect.Response[grpc.HouseworkDetailResponse], error)
	CreateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	UpdateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	FinishHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	DeleteHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error)
	GetHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemoRequest]) (*connect.Response[grpc.HouseworkMemoResponse], error)
	CreateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	UpdateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	DeleteHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error)
	GetHouseworkPoint(context.Context, *connect.Request[grpc.HouseworkPointRequest]) (*connect.Response[grpc.HouseworkPointResponse], error)
	GetHouseworkPointHistory(context.Context, *connect.Request[grpc.HouseworkPointHistoryRequest]) (*connect.Response[grpc.HouseworkPointHistoryResponse], error)
}

// NewHouseworkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHouseworkServiceHandler(svc HouseworkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	houseworkServiceGetHouseworkHandler := connect.NewUnaryHandler(
		HouseworkServiceGetHouseworkProcedure,
		svc.GetHousework,
		connect.WithSchema(houseworkServiceGetHouseworkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceGetHouseworkDetailHandler := connect.NewUnaryHandler(
		HouseworkServiceGetHouseworkDetailProcedure,
		svc.GetHouseworkDetail,
		connect.WithSchema(houseworkServiceGetHouseworkDetailMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceCreateHouseworkHandler := connect.NewUnaryHandler(
		HouseworkServiceCreateHouseworkProcedure,
		svc.CreateHousework,
		connect.WithSchema(houseworkServiceCreateHouseworkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceUpdateHouseworkHandler := connect.NewUnaryHandler(
		HouseworkServiceUpdateHouseworkProcedure,
		svc.UpdateHousework,
		connect.WithSchema(houseworkServiceUpdateHouseworkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceFinishHouseworkHandler := connect.NewUnaryHandler(
		HouseworkServiceFinishHouseworkProcedure,
		svc.FinishHousework,
		connect.WithSchema(houseworkServiceFinishHouseworkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceDeleteHouseworkHandler := connect.NewUnaryHandler(
		HouseworkServiceDeleteHouseworkProcedure,
		svc.DeleteHousework,
		connect.WithSchema(houseworkServiceDeleteHouseworkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceGetHouseworkMemoHandler := connect.NewUnaryHandler(
		HouseworkServiceGetHouseworkMemoProcedure,
		svc.GetHouseworkMemo,
		connect.WithSchema(houseworkServiceGetHouseworkMemoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceCreateHouseworkMemoHandler := connect.NewUnaryHandler(
		HouseworkServiceCreateHouseworkMemoProcedure,
		svc.CreateHouseworkMemo,
		connect.WithSchema(houseworkServiceCreateHouseworkMemoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceUpdateHouseworkMemoHandler := connect.NewUnaryHandler(
		HouseworkServiceUpdateHouseworkMemoProcedure,
		svc.UpdateHouseworkMemo,
		connect.WithSchema(houseworkServiceUpdateHouseworkMemoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceDeleteHouseworkMemoHandler := connect.NewUnaryHandler(
		HouseworkServiceDeleteHouseworkMemoProcedure,
		svc.DeleteHouseworkMemo,
		connect.WithSchema(houseworkServiceDeleteHouseworkMemoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceGetHouseworkPointHandler := connect.NewUnaryHandler(
		HouseworkServiceGetHouseworkPointProcedure,
		svc.GetHouseworkPoint,
		connect.WithSchema(houseworkServiceGetHouseworkPointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	houseworkServiceGetHouseworkPointHistoryHandler := connect.NewUnaryHandler(
		HouseworkServiceGetHouseworkPointHistoryProcedure,
		svc.GetHouseworkPointHistory,
		connect.WithSchema(houseworkServiceGetHouseworkPointHistoryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.HouseworkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HouseworkServiceGetHouseworkProcedure:
			houseworkServiceGetHouseworkHandler.ServeHTTP(w, r)
		case HouseworkServiceGetHouseworkDetailProcedure:
			houseworkServiceGetHouseworkDetailHandler.ServeHTTP(w, r)
		case HouseworkServiceCreateHouseworkProcedure:
			houseworkServiceCreateHouseworkHandler.ServeHTTP(w, r)
		case HouseworkServiceUpdateHouseworkProcedure:
			houseworkServiceUpdateHouseworkHandler.ServeHTTP(w, r)
		case HouseworkServiceFinishHouseworkProcedure:
			houseworkServiceFinishHouseworkHandler.ServeHTTP(w, r)
		case HouseworkServiceDeleteHouseworkProcedure:
			houseworkServiceDeleteHouseworkHandler.ServeHTTP(w, r)
		case HouseworkServiceGetHouseworkMemoProcedure:
			houseworkServiceGetHouseworkMemoHandler.ServeHTTP(w, r)
		case HouseworkServiceCreateHouseworkMemoProcedure:
			houseworkServiceCreateHouseworkMemoHandler.ServeHTTP(w, r)
		case HouseworkServiceUpdateHouseworkMemoProcedure:
			houseworkServiceUpdateHouseworkMemoHandler.ServeHTTP(w, r)
		case HouseworkServiceDeleteHouseworkMemoProcedure:
			houseworkServiceDeleteHouseworkMemoHandler.ServeHTTP(w, r)
		case HouseworkServiceGetHouseworkPointProcedure:
			houseworkServiceGetHouseworkPointHandler.ServeHTTP(w, r)
		case HouseworkServiceGetHouseworkPointHistoryProcedure:
			houseworkServiceGetHouseworkPointHistoryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHouseworkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHouseworkServiceHandler struct{}

func (UnimplementedHouseworkServiceHandler) GetHousework(context.Context, *connect.Request[grpc.HouseworkRequest]) (*connect.Response[grpc.HouseworkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.GetHousework is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) GetHouseworkDetail(context.Context, *connect.Request[grpc.HouseworkDetailRequest]) (*connect.Response[grpc.HouseworkDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.GetHouseworkDetail is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) CreateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.CreateHousework is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) UpdateHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.UpdateHousework is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) FinishHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.FinishHousework is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) DeleteHousework(context.Context, *connect.Request[grpc.Housework]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.DeleteHousework is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) GetHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemoRequest]) (*connect.Response[grpc.HouseworkMemoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.GetHouseworkMemo is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) CreateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.CreateHouseworkMemo is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) UpdateHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.UpdateHouseworkMemo is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) DeleteHouseworkMemo(context.Context, *connect.Request[grpc.HouseworkMemo]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.DeleteHouseworkMemo is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) GetHouseworkPoint(context.Context, *connect.Request[grpc.HouseworkPointRequest]) (*connect.Response[grpc.HouseworkPointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.GetHouseworkPoint is not implemented"))
}

func (UnimplementedHouseworkServiceHandler) GetHouseworkPointHistory(context.Context, *connect.Request[grpc.HouseworkPointHistoryRequest]) (*connect.Response[grpc.HouseworkPointHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.HouseworkService.GetHouseworkPointHistory is not implemented"))
}
