// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: point.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	grpc "shwgrpc/pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserPointServiceName is the fully-qualified name of the UserPointService service.
	UserPointServiceName = "shw.UserPointService"
	// FamilyPointServiceName is the fully-qualified name of the FamilyPointService service.
	FamilyPointServiceName = "shw.FamilyPointService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserPointServiceGetUserPointProcedure is the fully-qualified name of the UserPointService's
	// GetUserPoint RPC.
	UserPointServiceGetUserPointProcedure = "/shw.UserPointService/GetUserPoint"
	// UserPointServiceCreateUserPointProcedure is the fully-qualified name of the UserPointService's
	// CreateUserPoint RPC.
	UserPointServiceCreateUserPointProcedure = "/shw.UserPointService/CreateUserPoint"
	// UserPointServiceUpdateUserPointProcedure is the fully-qualified name of the UserPointService's
	// UpdateUserPoint RPC.
	UserPointServiceUpdateUserPointProcedure = "/shw.UserPointService/UpdateUserPoint"
	// UserPointServiceDeleteUserPointProcedure is the fully-qualified name of the UserPointService's
	// DeleteUserPoint RPC.
	UserPointServiceDeleteUserPointProcedure = "/shw.UserPointService/DeleteUserPoint"
	// FamilyPointServiceListFamilyPointsProcedure is the fully-qualified name of the
	// FamilyPointService's ListFamilyPoints RPC.
	FamilyPointServiceListFamilyPointsProcedure = "/shw.FamilyPointService/ListFamilyPoints"
)

// UserPointServiceClient is a client for the shw.UserPointService service.
type UserPointServiceClient interface {
	GetUserPoint(context.Context, *connect.Request[grpc.GetUserPointRequest]) (*connect.Response[grpc.GetUserPointResponse], error)
	CreateUserPoint(context.Context, *connect.Request[grpc.CreateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
	UpdateUserPoint(context.Context, *connect.Request[grpc.UpdateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
	DeleteUserPoint(context.Context, *connect.Request[grpc.DeleteUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewUserPointServiceClient constructs a client for the shw.UserPointService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserPointServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserPointServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userPointServiceMethods := grpc.File_point_proto.Services().ByName("UserPointService").Methods()
	return &userPointServiceClient{
		getUserPoint: connect.NewClient[grpc.GetUserPointRequest, grpc.GetUserPointResponse](
			httpClient,
			baseURL+UserPointServiceGetUserPointProcedure,
			connect.WithSchema(userPointServiceMethods.ByName("GetUserPoint")),
			connect.WithClientOptions(opts...),
		),
		createUserPoint: connect.NewClient[grpc.CreateUserPointRequest, grpc.CommonResponse](
			httpClient,
			baseURL+UserPointServiceCreateUserPointProcedure,
			connect.WithSchema(userPointServiceMethods.ByName("CreateUserPoint")),
			connect.WithClientOptions(opts...),
		),
		updateUserPoint: connect.NewClient[grpc.UpdateUserPointRequest, grpc.CommonResponse](
			httpClient,
			baseURL+UserPointServiceUpdateUserPointProcedure,
			connect.WithSchema(userPointServiceMethods.ByName("UpdateUserPoint")),
			connect.WithClientOptions(opts...),
		),
		deleteUserPoint: connect.NewClient[grpc.DeleteUserPointRequest, grpc.CommonResponse](
			httpClient,
			baseURL+UserPointServiceDeleteUserPointProcedure,
			connect.WithSchema(userPointServiceMethods.ByName("DeleteUserPoint")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userPointServiceClient implements UserPointServiceClient.
type userPointServiceClient struct {
	getUserPoint    *connect.Client[grpc.GetUserPointRequest, grpc.GetUserPointResponse]
	createUserPoint *connect.Client[grpc.CreateUserPointRequest, grpc.CommonResponse]
	updateUserPoint *connect.Client[grpc.UpdateUserPointRequest, grpc.CommonResponse]
	deleteUserPoint *connect.Client[grpc.DeleteUserPointRequest, grpc.CommonResponse]
}

// GetUserPoint calls shw.UserPointService.GetUserPoint.
func (c *userPointServiceClient) GetUserPoint(ctx context.Context, req *connect.Request[grpc.GetUserPointRequest]) (*connect.Response[grpc.GetUserPointResponse], error) {
	return c.getUserPoint.CallUnary(ctx, req)
}

// CreateUserPoint calls shw.UserPointService.CreateUserPoint.
func (c *userPointServiceClient) CreateUserPoint(ctx context.Context, req *connect.Request[grpc.CreateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createUserPoint.CallUnary(ctx, req)
}

// UpdateUserPoint calls shw.UserPointService.UpdateUserPoint.
func (c *userPointServiceClient) UpdateUserPoint(ctx context.Context, req *connect.Request[grpc.UpdateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateUserPoint.CallUnary(ctx, req)
}

// DeleteUserPoint calls shw.UserPointService.DeleteUserPoint.
func (c *userPointServiceClient) DeleteUserPoint(ctx context.Context, req *connect.Request[grpc.DeleteUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deleteUserPoint.CallUnary(ctx, req)
}

// UserPointServiceHandler is an implementation of the shw.UserPointService service.
type UserPointServiceHandler interface {
	GetUserPoint(context.Context, *connect.Request[grpc.GetUserPointRequest]) (*connect.Response[grpc.GetUserPointResponse], error)
	CreateUserPoint(context.Context, *connect.Request[grpc.CreateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
	UpdateUserPoint(context.Context, *connect.Request[grpc.UpdateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
	DeleteUserPoint(context.Context, *connect.Request[grpc.DeleteUserPointRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewUserPointServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserPointServiceHandler(svc UserPointServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userPointServiceMethods := grpc.File_point_proto.Services().ByName("UserPointService").Methods()
	userPointServiceGetUserPointHandler := connect.NewUnaryHandler(
		UserPointServiceGetUserPointProcedure,
		svc.GetUserPoint,
		connect.WithSchema(userPointServiceMethods.ByName("GetUserPoint")),
		connect.WithHandlerOptions(opts...),
	)
	userPointServiceCreateUserPointHandler := connect.NewUnaryHandler(
		UserPointServiceCreateUserPointProcedure,
		svc.CreateUserPoint,
		connect.WithSchema(userPointServiceMethods.ByName("CreateUserPoint")),
		connect.WithHandlerOptions(opts...),
	)
	userPointServiceUpdateUserPointHandler := connect.NewUnaryHandler(
		UserPointServiceUpdateUserPointProcedure,
		svc.UpdateUserPoint,
		connect.WithSchema(userPointServiceMethods.ByName("UpdateUserPoint")),
		connect.WithHandlerOptions(opts...),
	)
	userPointServiceDeleteUserPointHandler := connect.NewUnaryHandler(
		UserPointServiceDeleteUserPointProcedure,
		svc.DeleteUserPoint,
		connect.WithSchema(userPointServiceMethods.ByName("DeleteUserPoint")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.UserPointService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserPointServiceGetUserPointProcedure:
			userPointServiceGetUserPointHandler.ServeHTTP(w, r)
		case UserPointServiceCreateUserPointProcedure:
			userPointServiceCreateUserPointHandler.ServeHTTP(w, r)
		case UserPointServiceUpdateUserPointProcedure:
			userPointServiceUpdateUserPointHandler.ServeHTTP(w, r)
		case UserPointServiceDeleteUserPointProcedure:
			userPointServiceDeleteUserPointHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserPointServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserPointServiceHandler struct{}

func (UnimplementedUserPointServiceHandler) GetUserPoint(context.Context, *connect.Request[grpc.GetUserPointRequest]) (*connect.Response[grpc.GetUserPointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserPointService.GetUserPoint is not implemented"))
}

func (UnimplementedUserPointServiceHandler) CreateUserPoint(context.Context, *connect.Request[grpc.CreateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserPointService.CreateUserPoint is not implemented"))
}

func (UnimplementedUserPointServiceHandler) UpdateUserPoint(context.Context, *connect.Request[grpc.UpdateUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserPointService.UpdateUserPoint is not implemented"))
}

func (UnimplementedUserPointServiceHandler) DeleteUserPoint(context.Context, *connect.Request[grpc.DeleteUserPointRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserPointService.DeleteUserPoint is not implemented"))
}

// FamilyPointServiceClient is a client for the shw.FamilyPointService service.
type FamilyPointServiceClient interface {
	ListFamilyPoints(context.Context, *connect.Request[grpc.ListFamilyPointsRequest]) (*connect.Response[grpc.ListFamilyPointsResponse], error)
}

// NewFamilyPointServiceClient constructs a client for the shw.FamilyPointService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFamilyPointServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FamilyPointServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	familyPointServiceMethods := grpc.File_point_proto.Services().ByName("FamilyPointService").Methods()
	return &familyPointServiceClient{
		listFamilyPoints: connect.NewClient[grpc.ListFamilyPointsRequest, grpc.ListFamilyPointsResponse](
			httpClient,
			baseURL+FamilyPointServiceListFamilyPointsProcedure,
			connect.WithSchema(familyPointServiceMethods.ByName("ListFamilyPoints")),
			connect.WithClientOptions(opts...),
		),
	}
}

// familyPointServiceClient implements FamilyPointServiceClient.
type familyPointServiceClient struct {
	listFamilyPoints *connect.Client[grpc.ListFamilyPointsRequest, grpc.ListFamilyPointsResponse]
}

// ListFamilyPoints calls shw.FamilyPointService.ListFamilyPoints.
func (c *familyPointServiceClient) ListFamilyPoints(ctx context.Context, req *connect.Request[grpc.ListFamilyPointsRequest]) (*connect.Response[grpc.ListFamilyPointsResponse], error) {
	return c.listFamilyPoints.CallUnary(ctx, req)
}

// FamilyPointServiceHandler is an implementation of the shw.FamilyPointService service.
type FamilyPointServiceHandler interface {
	ListFamilyPoints(context.Context, *connect.Request[grpc.ListFamilyPointsRequest]) (*connect.Response[grpc.ListFamilyPointsResponse], error)
}

// NewFamilyPointServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFamilyPointServiceHandler(svc FamilyPointServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	familyPointServiceMethods := grpc.File_point_proto.Services().ByName("FamilyPointService").Methods()
	familyPointServiceListFamilyPointsHandler := connect.NewUnaryHandler(
		FamilyPointServiceListFamilyPointsProcedure,
		svc.ListFamilyPoints,
		connect.WithSchema(familyPointServiceMethods.ByName("ListFamilyPoints")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.FamilyPointService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FamilyPointServiceListFamilyPointsProcedure:
			familyPointServiceListFamilyPointsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFamilyPointServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFamilyPointServiceHandler struct{}

func (UnimplementedFamilyPointServiceHandler) ListFamilyPoints(context.Context, *connect.Request[grpc.ListFamilyPointsRequest]) (*connect.Response[grpc.ListFamilyPointsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.FamilyPointService.ListFamilyPoints is not implemented"))
}
