// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: point.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	grpc "shwgrpc/pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PointServiceName is the fully-qualified name of the PointService service.
	PointServiceName = "shw.PointService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PointServiceGetPointProcedure is the fully-qualified name of the PointService's GetPoint RPC.
	PointServiceGetPointProcedure = "/shw.PointService/GetPoint"
	// PointServiceGetFamilyPointListProcedure is the fully-qualified name of the PointService's
	// GetFamilyPointList RPC.
	PointServiceGetFamilyPointListProcedure = "/shw.PointService/GetFamilyPointList"
	// PointServiceCreatePointProcedure is the fully-qualified name of the PointService's CreatePoint
	// RPC.
	PointServiceCreatePointProcedure = "/shw.PointService/CreatePoint"
	// PointServiceUpdatePointProcedure is the fully-qualified name of the PointService's UpdatePoint
	// RPC.
	PointServiceUpdatePointProcedure = "/shw.PointService/UpdatePoint"
	// PointServiceDeletePointProcedure is the fully-qualified name of the PointService's DeletePoint
	// RPC.
	PointServiceDeletePointProcedure = "/shw.PointService/DeletePoint"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	pointServiceServiceDescriptor                  = grpc.File_point_proto.Services().ByName("PointService")
	pointServiceGetPointMethodDescriptor           = pointServiceServiceDescriptor.Methods().ByName("GetPoint")
	pointServiceGetFamilyPointListMethodDescriptor = pointServiceServiceDescriptor.Methods().ByName("GetFamilyPointList")
	pointServiceCreatePointMethodDescriptor        = pointServiceServiceDescriptor.Methods().ByName("CreatePoint")
	pointServiceUpdatePointMethodDescriptor        = pointServiceServiceDescriptor.Methods().ByName("UpdatePoint")
	pointServiceDeletePointMethodDescriptor        = pointServiceServiceDescriptor.Methods().ByName("DeletePoint")
)

// PointServiceClient is a client for the shw.PointService service.
type PointServiceClient interface {
	GetPoint(context.Context, *connect.Request[grpc.PointRequest]) (*connect.Response[grpc.PointResponse], error)
	GetFamilyPointList(context.Context, *connect.Request[grpc.FamilyPointListRequest]) (*connect.Response[grpc.FamilyPointList], error)
	CreatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
	UpdatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
	DeletePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
}

// NewPointServiceClient constructs a client for the shw.PointService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPointServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PointServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &pointServiceClient{
		getPoint: connect.NewClient[grpc.PointRequest, grpc.PointResponse](
			httpClient,
			baseURL+PointServiceGetPointProcedure,
			connect.WithSchema(pointServiceGetPointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getFamilyPointList: connect.NewClient[grpc.FamilyPointListRequest, grpc.FamilyPointList](
			httpClient,
			baseURL+PointServiceGetFamilyPointListProcedure,
			connect.WithSchema(pointServiceGetFamilyPointListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createPoint: connect.NewClient[grpc.Point, grpc.CommonResponse](
			httpClient,
			baseURL+PointServiceCreatePointProcedure,
			connect.WithSchema(pointServiceCreatePointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updatePoint: connect.NewClient[grpc.Point, grpc.CommonResponse](
			httpClient,
			baseURL+PointServiceUpdatePointProcedure,
			connect.WithSchema(pointServiceUpdatePointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deletePoint: connect.NewClient[grpc.Point, grpc.CommonResponse](
			httpClient,
			baseURL+PointServiceDeletePointProcedure,
			connect.WithSchema(pointServiceDeletePointMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// pointServiceClient implements PointServiceClient.
type pointServiceClient struct {
	getPoint           *connect.Client[grpc.PointRequest, grpc.PointResponse]
	getFamilyPointList *connect.Client[grpc.FamilyPointListRequest, grpc.FamilyPointList]
	createPoint        *connect.Client[grpc.Point, grpc.CommonResponse]
	updatePoint        *connect.Client[grpc.Point, grpc.CommonResponse]
	deletePoint        *connect.Client[grpc.Point, grpc.CommonResponse]
}

// GetPoint calls shw.PointService.GetPoint.
func (c *pointServiceClient) GetPoint(ctx context.Context, req *connect.Request[grpc.PointRequest]) (*connect.Response[grpc.PointResponse], error) {
	return c.getPoint.CallUnary(ctx, req)
}

// GetFamilyPointList calls shw.PointService.GetFamilyPointList.
func (c *pointServiceClient) GetFamilyPointList(ctx context.Context, req *connect.Request[grpc.FamilyPointListRequest]) (*connect.Response[grpc.FamilyPointList], error) {
	return c.getFamilyPointList.CallUnary(ctx, req)
}

// CreatePoint calls shw.PointService.CreatePoint.
func (c *pointServiceClient) CreatePoint(ctx context.Context, req *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return c.createPoint.CallUnary(ctx, req)
}

// UpdatePoint calls shw.PointService.UpdatePoint.
func (c *pointServiceClient) UpdatePoint(ctx context.Context, req *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updatePoint.CallUnary(ctx, req)
}

// DeletePoint calls shw.PointService.DeletePoint.
func (c *pointServiceClient) DeletePoint(ctx context.Context, req *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return c.deletePoint.CallUnary(ctx, req)
}

// PointServiceHandler is an implementation of the shw.PointService service.
type PointServiceHandler interface {
	GetPoint(context.Context, *connect.Request[grpc.PointRequest]) (*connect.Response[grpc.PointResponse], error)
	GetFamilyPointList(context.Context, *connect.Request[grpc.FamilyPointListRequest]) (*connect.Response[grpc.FamilyPointList], error)
	CreatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
	UpdatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
	DeletePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error)
}

// NewPointServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPointServiceHandler(svc PointServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pointServiceGetPointHandler := connect.NewUnaryHandler(
		PointServiceGetPointProcedure,
		svc.GetPoint,
		connect.WithSchema(pointServiceGetPointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pointServiceGetFamilyPointListHandler := connect.NewUnaryHandler(
		PointServiceGetFamilyPointListProcedure,
		svc.GetFamilyPointList,
		connect.WithSchema(pointServiceGetFamilyPointListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pointServiceCreatePointHandler := connect.NewUnaryHandler(
		PointServiceCreatePointProcedure,
		svc.CreatePoint,
		connect.WithSchema(pointServiceCreatePointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pointServiceUpdatePointHandler := connect.NewUnaryHandler(
		PointServiceUpdatePointProcedure,
		svc.UpdatePoint,
		connect.WithSchema(pointServiceUpdatePointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	pointServiceDeletePointHandler := connect.NewUnaryHandler(
		PointServiceDeletePointProcedure,
		svc.DeletePoint,
		connect.WithSchema(pointServiceDeletePointMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.PointService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PointServiceGetPointProcedure:
			pointServiceGetPointHandler.ServeHTTP(w, r)
		case PointServiceGetFamilyPointListProcedure:
			pointServiceGetFamilyPointListHandler.ServeHTTP(w, r)
		case PointServiceCreatePointProcedure:
			pointServiceCreatePointHandler.ServeHTTP(w, r)
		case PointServiceUpdatePointProcedure:
			pointServiceUpdatePointHandler.ServeHTTP(w, r)
		case PointServiceDeletePointProcedure:
			pointServiceDeletePointHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPointServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPointServiceHandler struct{}

func (UnimplementedPointServiceHandler) GetPoint(context.Context, *connect.Request[grpc.PointRequest]) (*connect.Response[grpc.PointResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.PointService.GetPoint is not implemented"))
}

func (UnimplementedPointServiceHandler) GetFamilyPointList(context.Context, *connect.Request[grpc.FamilyPointListRequest]) (*connect.Response[grpc.FamilyPointList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.PointService.GetFamilyPointList is not implemented"))
}

func (UnimplementedPointServiceHandler) CreatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.PointService.CreatePoint is not implemented"))
}

func (UnimplementedPointServiceHandler) UpdatePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.PointService.UpdatePoint is not implemented"))
}

func (UnimplementedPointServiceHandler) DeletePoint(context.Context, *connect.Request[grpc.Point]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.PointService.DeletePoint is not implemented"))
}
