// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user.proto

package grpcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	grpc "shwgrpc/pkg/grpc"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "shw.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceListFamilyUsersProcedure is the fully-qualified name of the UserService's
	// ListFamilyUsers RPC.
	UserServiceListFamilyUsersProcedure = "/shw.UserService/ListFamilyUsers"
	// UserServiceUpdateUserRoleProcedure is the fully-qualified name of the UserService's
	// UpdateUserRole RPC.
	UserServiceUpdateUserRoleProcedure = "/shw.UserService/UpdateUserRole"
)

// UserServiceClient is a client for the shw.UserService service.
type UserServiceClient interface {
	ListFamilyUsers(context.Context, *connect.Request[grpc.ListFamilyUsersRequest]) (*connect.Response[grpc.ListFamilyUsersResponse], error)
	UpdateUserRole(context.Context, *connect.Request[grpc.UpdateUserRoleRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewUserServiceClient constructs a client for the shw.UserService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := grpc.File_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		listFamilyUsers: connect.NewClient[grpc.ListFamilyUsersRequest, grpc.ListFamilyUsersResponse](
			httpClient,
			baseURL+UserServiceListFamilyUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListFamilyUsers")),
			connect.WithClientOptions(opts...),
		),
		updateUserRole: connect.NewClient[grpc.UpdateUserRoleRequest, grpc.CommonResponse](
			httpClient,
			baseURL+UserServiceUpdateUserRoleProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUserRole")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	listFamilyUsers *connect.Client[grpc.ListFamilyUsersRequest, grpc.ListFamilyUsersResponse]
	updateUserRole  *connect.Client[grpc.UpdateUserRoleRequest, grpc.CommonResponse]
}

// ListFamilyUsers calls shw.UserService.ListFamilyUsers.
func (c *userServiceClient) ListFamilyUsers(ctx context.Context, req *connect.Request[grpc.ListFamilyUsersRequest]) (*connect.Response[grpc.ListFamilyUsersResponse], error) {
	return c.listFamilyUsers.CallUnary(ctx, req)
}

// UpdateUserRole calls shw.UserService.UpdateUserRole.
func (c *userServiceClient) UpdateUserRole(ctx context.Context, req *connect.Request[grpc.UpdateUserRoleRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return c.updateUserRole.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the shw.UserService service.
type UserServiceHandler interface {
	ListFamilyUsers(context.Context, *connect.Request[grpc.ListFamilyUsersRequest]) (*connect.Response[grpc.ListFamilyUsersResponse], error)
	UpdateUserRole(context.Context, *connect.Request[grpc.UpdateUserRoleRequest]) (*connect.Response[grpc.CommonResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := grpc.File_user_proto.Services().ByName("UserService").Methods()
	userServiceListFamilyUsersHandler := connect.NewUnaryHandler(
		UserServiceListFamilyUsersProcedure,
		svc.ListFamilyUsers,
		connect.WithSchema(userServiceMethods.ByName("ListFamilyUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserRoleHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserRoleProcedure,
		svc.UpdateUserRole,
		connect.WithSchema(userServiceMethods.ByName("UpdateUserRole")),
		connect.WithHandlerOptions(opts...),
	)
	return "/shw.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceListFamilyUsersProcedure:
			userServiceListFamilyUsersHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserRoleProcedure:
			userServiceUpdateUserRoleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) ListFamilyUsers(context.Context, *connect.Request[grpc.ListFamilyUsersRequest]) (*connect.Response[grpc.ListFamilyUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserService.ListFamilyUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUserRole(context.Context, *connect.Request[grpc.UpdateUserRoleRequest]) (*connect.Response[grpc.CommonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("shw.UserService.UpdateUserRole is not implemented"))
}
